### ISSUE TITLE
small changes to install.sh

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#104]
I needed to add these two lines:

sudo apt-get update
sudo apt-get install python-tk

**Comment by ags-tolson** [comment]
May I ask why pythonn-tk?  I'm sure it'll be fine to go in, just want to know what for.

**Comment by bhbraswell** [comment]
I have absolutely no idea. From the trace it looks possibly like it's a probably not necessary dependency of the 6S model code.

**Comment by ags-tolson** [comment]
Okay, that might be good enough to justify it since Tk is bundled with python most of the time to begin with.
