### ISSUE TITLE
Densify modis tiles

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#108]
This is a remnant from less well organized times, but:
/data/modis/make_tiles.py was written to create more "densified" tiles. This is necessary for more accurate calculation of intersection when the user-provided geometry is not in EPSG:4326. Currently the tiles are just four corners which can be problematic. 

Though this script is there, apparently the result of the script (a new tiles.shp file) was not preserved.

The task is to modify the make_tiles script so that h and v attributes are also there (because the driver concatenates and uses them) and to create and check the new tiles vector.

**Comment by ircwaves** [comment]
```
{
    "geometry": {
        "coordinates": [[[-19649629.666666668, -10010000.0], [-20020000.0, -10010000.0], [-20020000.0, -8898889.0], [-19649629.666666668, -8898889.0], [-19279259.333333336, -8898889.0], [-18908889.0, -8898889.0], [-18908889.0, -10010000.0], [-19279259.333333336, -10010000.0], [-19649629.666666668, -10010000.0]]],
         "type": "Polygon"
    },
    "id": "0",
    "properties": {
        "cat": 1,
        "h": 0,
        "v": 17},
    "type": "Feature"
}
```
Looks like this is done, correct @bhbraswell ?

**Comment by bhbraswell** [comment]
Yes
