### ISSUE TITLE
replace direct filesystem usage with consistent temp file method

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#115]
Say GIPS is doing a fetch, and downloading a file to the stage.  If the download breaks halfway through, GIPS will stop and report the error.  However, the file will remain in the stage.

Establish the use of temp files to mitigate this problem:  Only move things into the stage (or archive) when the file has been created or fetched successfully.

**Comment by ags-tolson** [comment]
Example of place to change:

in `inventory/__init__.py:class DataInventory::__init__():`, line 264

`dataclass.fetch(self.products.base, self.spatial.tiles, self.temporal, self.update)`

**Comment by justinfisk** [comment]
This should also apply to ```process```, right?

**Comment by ircwaves** [comment]
This should also apply to `process` in every driver.

**Comment by ircwaves** [comment]
@ags-tolson IIRC, you implemented something to address this issue.  Is that correct?

**Comment by ags-tolson** [comment]
Yes it merged with the first sentinel-2 PR I believe:

`def make_temp_dir(suffix='', prefix='tmp', dir=None):` <-- in `gips.utils`:

https://github.com/Applied-GeoSolutions/gips/blob/e9e10fd99ac5b3b4968ee0f7478c3ab5e6709e96/gips/utils.py#L144-L157

**Comment by ags-tolson** [comment]
PS - example of use:

https://github.com/Applied-GeoSolutions/gips/blob/e9e10fd99ac5b3b4968ee0f7478c3ab5e6709e96/gips/data/sentinel2/sentinel2.py#L400

**Comment by ircwaves** [comment]
OK.  This needs to be diseminated throughout the code base.  But that should get its own issue.  I'll write that up.
