### ISSUE TITLE
MERRA Pydap needs EarthData auth

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#118]
working on it

**Comment by bhbraswell** [comment]
Serious rabbit hole. Having less fun than Alice.

**Comment by bhbraswell** [comment]
> Hi -
>
> I am unable to access MERRA data using PyDAP. I can download MERRA using wget or a browser. 
> 
> I am following the instructions here: https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+PyDAP
> 
> And also have tried the directions here: http://disc.sci.gsfc.nasa.gov/registration/registration-for-data-access
> 
> which are somewhat different (install_cas_client, as opposed to install_basic_client)
> 
> I have a .netrc file, and have enabled PyDAP application through my EarthData settings.
> 
> I am attempting to access from 132.177.240.105, intermittentently from Nov. 25th to the 27th (today). My username is bobbyhbraswell. My OS is Ubuntu 16.04. PyDAP version is 3.1.1.
> 
> The lines of Python I am using to test are as follows:
> 
> ```
> # test.py
> 
> from install_basic_client import install_basic_client
> install_basic_client()
> 
> from pydap.client import open_url
> 
> loc = "http://goldsmr4.gesdisc.eosdis.nasa.gov:80/opendap/MERRA2/M2T1NXSLV.5.12.4/1996/10/MERRA2_200.tavg1_2d_slv_Nx.19961003.nc4"
> 
> dataset = open_url(loc)
> 
> var = dataset['T2M']
> 
> print var.shape
> print var[0,10:12,10:12]
> ```
> 
> I get a 400 error. Full traceback pasted below.
> 
> The line in install_basic_client that it is choking on is:
> r = urllib2.urlopen(url)
> 
> The url that is causing the failure is:
> http://goldsmr4.gesdisc.eosdis.nasa.gov:80/opendap/MERRA2/M2T1NXSLV.5.12.4/1996/10/MERRA2_200.tavg1_2d_slv_Nx.19961003.nc4.dods?T2M[0:1:0][10:1:11][10:1:11]&
> 
> Thanks for any help you can provide.
> 
> ```
> No handlers could be found for logger "install_basic_client"
> (24, 361, 576)
> Traceback (most recent call last):
>   File "./test.py", line 30, in <module>
>     print var[0,10:12,10:12]
>   File "/home/braswell/gips/.venv/local/lib/python2.7/site-packages/pydap/model.py", line 192, in __getitem__
>     return self.data[index]
>   File "/home/braswell/gips/.venv/local/lib/python2.7/site-packages/pydap/proxy.py", line 115, in __getitem__
>     resp, data = request(url)
>   File "/home/braswell/gips/gips/data/merra/install_basic_client.py", line 46, in new_request
>     r = urllib2.urlopen(url)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in url open
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hers)
>   File "/usr/lib/python2.7/urllib2.py", line 467, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hers)
>   File "/usr/lib/python2.7/urllib2.py", line 467, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 909, in http_error_401
>     url, req, headers)
>   File "/usr/lib/python2.7/urllib2.py", line 887, in http_error_auth_reqed
>     return self.retry_http_basic_auth(host, req, realm)
>   File "/usr/lib/python2.7/urllib2.py", line 897, in retry_http_basic_auth
>     return self.parent.open(req, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hers)
>   File "/usr/lib/python2.7/urllib2.py", line 467, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hers)
>   File "/usr/lib/python2.7/urllib2.py", line 467, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hers)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 400: Bad Request
> ```
>

**Comment by bhbraswell** [comment]
One option is to rewrite the driver to work without PyDAP. All the data are available online. The reason we went with using the opendap method is that the archived files are .nc4 with dozens of variables, most of which we don't use. But, they aren't super large ~500MB. So these files would become the assets instead of the variable-specific assets we have now.

**Comment by bhbraswell** [comment]
Sorry this issue is redundant with #99

**Comment by ircwaves** [comment]
@bhbraswell can you report the output from the following command from your container?
```
dpkg -l | grep -i netcdf
```

I ask for that because I know that on 14.04 it is an older version, and the pydap section of the goddard link says:

+ PyDAP- provides both an interface for python programs to read from OPeNDAP servers and the netCDF4 python module which uses the netCDF-C library to actually access data.

    - Check version of the netCDF-C library that the application uses. Once the application has updated to version 4.3.3.1 or later, authentication configuration should be the same as for ncdump.

On `rio` I am able to find out which package `python-netcdf4` is using via the following:
```
icooke@rio:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> [CONTROL-Z]
[1]+  Stopped                 python
icooke@rio:~$ ps -fu icooke | grep python         # find the pid
icooke   75483 75184  0 09:51 pts/0    00:00:00 python
icooke   75523 75184  0 09:55 pts/0    00:00:00 grep --color=auto python
icooke@rio:~$ lsof -p 75483| grep -i netcdf          # find the .so being used
python  75483 icooke  mem    REG    8,1  1246112   286084 /usr/lib/libnetcdf.so.7.1.1
python  75483 icooke  mem    REG    8,1   890048   270066 /usr/lib/python2.7/dist-packages/netCDF4.so
icooke@rio:~$ dpkg -S /usr/lib/libnetcdf.so.7.1.1           # find which package it belongs to 
libnetcdfc7: /usr/lib/libnetcdf.so.7.1.1
icooke@rio:~$ dpkg -l libnetcdfc7
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libnetcdfc7    1:4.1.3-7ubu amd64        Interface for scientific data acc
```
which seems to indicate that it is version 4.1.3.x on ubuntu 14.04.  and seems (by similar digging) 4.4.0.x on 16.04.

**Comment by bhbraswell** [comment]
```
(.venv) (screen)braswell@sci3:~/gips/gips/data/merra$ dpkg -l | grep -i netcdf
ii  libhdf4-0-alt                          4.2.10-3.2                               amd64        Hierarchical Data Format library (without NetCDF)
ii  libhdf4-alt-dev                        4.2.10-3.2                               amd64        Hierarchical Data Format development files (without NetCDF)
ii  libnetcdf-dev                          1:4.4.0-2                                amd64        creation, access, and sharing of scientific data
ii  libnetcdf11                            1:4.4.0-2                                amd64        Interface for scientific data access to large binary data
ii  netcdf-bin                             1:4.4.0-2                                amd64        Programs for reading and writing NetCDF files
ii  python-netcdf4                         1.2.2-2                                  amd64        Python interface to the netCDF4 (network Common Data Form) library
```

**Comment by bhbraswell** [comment]
I believe rewriting the driver to fetch the actual nc4 data set using httplib instead of getting a single variable with pydap is making more sense. It won't be a lot of work, it will be consistent with other drivers, and reduce or avoid additional dependencies. The MERRA grid is already global, so that won't need to change.

**Comment by bhbraswell** [comment]
Can't believe I missed this, but also don't know why it's like this.

> Hi Bobby,
> 
> The problem is with '&' at the end of 
> http://goldsmr4.gesdisc.eosdis.nasa.gov:80/opendap/MERRA2/M2T1NXSLV.5.12.4/1996/10/MERRA2_200.tavg1_2d_slv_Nx.19961003.nc4.dods?T2M[0:1:0][10:1:11][10:1:11]&
> 
> which is added by PyDAP library. 
> 
> You could take the code for install_basic_client() here https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+PyDAP
> and replace lines for new_request(url) with following:
> 
> def new_request(url):
>         if url[-1] is '&': url = url[0:-1]
>         log.debug('Opening %s (install_basic_client)' % url)
>         r = urllib2.urlopen(url)
>         resp = r.headers.dict
> 
> Please let me know if it helps,
> Thanks!
> Irina
> 

Seems to work in my test case. I'll clean up and push the result.

**Comment by ags-tolson** [comment]
Don't use `is` the way they do, they're doing it wrong.  `is` is for establishing object identity only.  Use `==` for establish value equivalence.  `is` only does the right thing here as a side effect of the implementation of CPython.  In our glorious new world of unicode and ascii in the same runtime, you have to be careful to use the right one:

```
>>> u'&' is '&'
False
>>> u'&' == '&'
True
```

**Comment by ircwaves** [comment]
Complete MERRA rewrite crushed this issue.

**Comment by bhbraswell** [comment]
So done

**Comment by ags-tolson** [comment]
ohhhhhh
:hand:
:arrow_down:
:microphone:
