### ISSUE TITLE
Is gips_project without -p an actual use case?

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#119]
The current behavior of gips_project [asset] without -p is to loop over all the products. This might be convenient for testing, but also is probably unnecessary since I don't think there is any example in practice where we do this. However since -p accepts more than one argument I think the real question going forward is whether a request to GIPS should be for one product at a time. This question is relevant to geokit.

**Comment by ags-tolson** [comment]
It would simplify the code to remove the looping behavior (looping over product types that is).  However I think this assumption is in the deep structure of the code, so the process of removing that looping behavior may not be fast and easy.  I always endorse simplifying code by removing unused or unneeded features, but it might be work to get there is all.

**Comment by bhbraswell** [comment]
I think we decided that the answer is "yes" at least for now.
