### ISSUE TITLE
data catalog population

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#120]
Something that runs at gips configuration time to populate the data catalog table (describe what products are available). 

Some thoughts on how it would work:

Loop through the settings to find available drivers
Loop through the product drivers finding _products dictionary

Will need to add dictionary per product in driver that describes which bands are which
Populate product name and description, bands in data catalog table

**Comment by ircwaves** [comment]
1. add `bandnames` dictionary to the `_products` dictionary of each driver `Data` class, and use it to set the band descriptions for each product created.
2. add data catalog function `gips.utils` which iterates over the configured drivers ( there are good examples in that module) and returns a dictionary of the info.
3. wire `gips.utils.data_catalog()` into `gips_config` such that it populates an ORM table at configure time.

**Comment by ircwaves** [comment]
This portion of the datacatalog is done.
