### ISSUE TITLE
Earth Data credentials outside individual driver settings

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#122]
Currently, Earth Data auth credentials are inside individual data driver parts of the settings.py REPOS dictionary. 

However these are also needed for ASTER, MERRA, probably eventually Landsat, possibly others.

Can this be moved outside the REPOS dictionary so it can be shared among entries?

**Comment by ags-tolson** [comment]
Yeah, should be easy to just add an all-caps item to the settings templates, `EARTHDATA_CREDENTIALS` or something, and rework modis a bit so it looks there instead of `REPOS`.  Then other drivers can be set up to do the same, as needed.

**Comment by ircwaves** [comment]
7507121
