### ISSUE TITLE
insert 'requested' assets and products into the DB

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#124]
For the purposes of the batch scheduler / data handler, need to create a new entrance to gips (```gips_query```?) that determines which ```products``` and associated ```assets``` are needed for a given processing request and inserts records into the DB with status ```requested```

In order to do this, the ```gips.data.core.*.fetch``` mechanism needs to be overhauled.  ‘fetch’ within gips means ```query``` and ```download``` sequentially.  We can leave those options there, but the logical operations need to be made into their own separate functions.

Will require a new django model to track dependencies between ```products``` and ```assets``` so the scheduler component can determine which tasks are ready to execute

**Comment by ircwaves** [comment]
proto-level code implemented and merged with #140

**Comment by ircwaves** [comment]
thanks for `.save()`ing me
