### ISSUE TITLE
bifurcate fetch into `query` and `fetch`

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#131]
`fetch` will still exist as composition of the two

**Comment by ircwaves** [comment]
Implemented for modis.  Need to implement for Landsat and Merra still, so leaving open.

**Comment by ircwaves** [comment]
I believe that in order to finish this out, only `${driver}Asset.fetch` needs to be broken out into `query` and `fetch` for:
+ May
  - [ ] merra
  - [ ] landsat 
  - [ ] daymet
+ May or later
  - [ ] prism
  - [ ] sentinel2
  - [ ] aod

 _edit and add pointer to commit or PR if checking a box._

**Comment by ags-tolson** [comment]
For sentinel2 there will be comments in the driver to help with this - search for "issue #131" in `sentinel2.py`

**Comment by bhbraswell** [comment]
In dev, I see that only merra has the query/fetch mechanism. This has been handled for some drivers in the batch-scheduler branch. But which drivers? Can we make a list? 

In general I think that even though batch scheduler creates this requirement, it should be implemented on a branch of current dev because it's easier to work there.

**Comment by ags-tolson** [comment]
@bhbraswell re what branch, I think you're right that dev is a better choice than b-s because b-s remains synced with dev, so if you do it there it ends up being done in both places.

**Comment by ircwaves** [comment]
Agreed.  MODIS work got done in `batch-scheduler` as it was part of the DH-push earlier this year.

@bhbraswell The only list I have is in my comment above.  Are there items missing there?

**Comment by ags-tolson** [comment]
#272 - PR for daymet

**Comment by ags-tolson** [comment]
With #338 merging I think this is resolved.
