### ISSUE TITLE
MERRA grid

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#138]
How do we deal with a raster product that is defined on grid points rather than area based?

The MERRA2 grid is:
lon = -180. + dlon * i;  (i = 1, 576)
lat = -90 + dlat * j;  (j = 1, 361)

Thus lat values range from -90 to 90. And lon values range from -180 to 179.375.

The MERRA data values are sampled at the points indicated by the formula above.

The .nc4 files look like this:
```
Driver: netCDF/Network Common Data Format
Files: MERRA2_400.tavg1_2d_slv_Nx.20161031.nc4
Size is 576, 361
Coordinate System is `'
Origin = (-180.312500000000000,90.250000000000000)
Pixel Size = (0.625000000000000,-0.500000000000000)
```

So I think they solve the problem by setting the geotransform so that the upper left corner is the **bounding box** upper left corner. Maybe this is consistent with what others have seen/ done.

**Comment by ircwaves** [comment]
That metadata looks like the file is (in GeoTIFF parlance) adjusted to be in "PixelIsArea" space, even though the data are sampled points.  `(-180.3125, 90.25)` is the upper left corner of the UL pixel, and the center of that pixel lines up with where the MERRA2 grid point is defined.

I think your i and j need to be decremented in the merra2 grid formulas above:
```python
>>> dlon, dlat = 0.625, -0.5
>>> map(lambda i: -180 + dlon * i, [1, 576])
[-179.375, 180.0]
>>> map(lambda j: 90 + dlat * j, [1, 361])
[89.5, -90.5]
```
but I believe that your bounding box idea is what is commonly done.

**Comment by bhbraswell** [comment]
Poorly framed question on my part. #142 will include handling the data grid.
