### ISSUE TITLE
MERRA driver rewrite

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#142]
MERRA now has a data pool, like MODIS. So the driver can be rewritten to eliminate the requirement of PyDAP and thus remove PyDAP from GIPS overall. This will also allow us to know the full file name before fetching instead of having to guess it.

This will supercede #118  and #138. I will close them.

**Comment by ircwaves** [comment]
:+1:

**Comment by bhbraswell** [comment]
MERRA rewrite (branch 142_merra) is now at WFM status. I request some assistance getting it into PR shape.

**Comment by ags-tolson** [comment]
https://github.com/Applied-GeoSolutions/gips/tree/142-merra <- link for convenience

**Comment by bhbraswell** [comment]
A side effect of these changes is that the MERRA profile will not work.
Note MERRA doesn't work at all now so this rewrite is not breaking profile.
See #155 (move profile to somewhere)

**Comment by bhbraswell** [comment]
Now addresses #165

**Comment by bhbraswell** [comment]
Will try to construct test case based on
```
rm -rf /data/gips/merra/tiles/*
gips_inventory merra --rectify
gips_process merra -d 1980-001,1980-002 -t h01v01 --fetch -v4
```

**Comment by ircwaves** [comment]
@bhbraswell -- I think this is closed based on the tests being implemented and merged into `dev`

**Comment by bhbraswell** [comment]
Agree - thanks
