### ISSUE TITLE
Is it possible to get exception with more detail?

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#145]
I'm working on the merra driver and get the message below. How can I either un-catch the error and see the full trace, or somehow get a message that is informative enough to find the problem, e.g. that shows line number?

```
(.venv) braswell@sci3:~/gips/gips$ gips_inventory merra -v4
GIPS Data Inventory (v0.9.0-dev)
Retrieving inventory for site tiles
Fatal: 1 error(s) occurred:
Error: list index out of range
```

**Comment by ags-tolson** [comment]
Yes:  Error handling & reporting in GIPS needs additional work I'm afraid.  In the mean time you can find `gips.utils.gips_exit` and set `show_tb=True` in the call to `report_error`.  Here's the line:

https://github.com/Applied-GeoSolutions/gips/blob/dev/gips/utils.py#L430

That should give you the full traceback.

**Comment by ags-tolson** [comment]
UGH!  The logic for controlling traceback appearance with the user's selected verbosity is already present in `report_error`.  I think `show_tb=True` on line 430 is safe to put into dev and will solve the problem.

**Comment by bhbraswell** [comment]
setting ```show_tb=True``` seemed to do the trick. Thanks!

**Comment by ircwaves** [comment]
maybe it should be 
```python
show_tb=gippy.Options.Verbose() >= _traceback_verbosity
```
so it is easily engaged and disengaged?  Seems like that might have been where @ags-tolson was headed.

**Comment by ags-tolson** [comment]
@ircwaves That's what I'm saying above:  You'r idea is pretty much what I actually did, except I made an override it with `show_tb`, then proceeded to misuse it.

**Comment by bhbraswell** [comment]
Any idea what it means when you get nothing at all?

```
(.venv) braswell@sci3:~/gips_merra$ gips_inventory merra -p tave -d 2010-001 -v4 --fetch
GIPS Data Inventory (v0.9.0-dev)
(.venv) braswell@sci3:~/gips_merra$ 
```

**Comment by bhbraswell** [comment]
Not specifying spatial extent or tile was the problem. This give a regular error.
```
(.venv) braswell@sci3:~/gips_merra$ gips_inventory merra -p tave -d 2010-001 -t h01v01 -v4 --fetch
... cool error stuff ...
```
Note: expected behavior is to give an error when -t or -s is not present.

**Comment by ags-tolson** [comment]
Does merra not let you do the standard `gips_inventory` behavior and show you the whole inventory in that case?  Like `gips_inventory modis # no options here`?

**Comment by ags-tolson** [comment]
assuming the question is adequately answered since it sat silent for a week

**Comment by bhbraswell** [comment]
Yes, thanks.
