### ISSUE TITLE
archive failure

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#147]
batch-scheduler related...

I encounter this issue if an asset is 'requested' but the file already exists on the filesystem. 

```Retrieved MCD43A4.A2012336.h12v04.006.2016112010833.hdf
/net/cluster/scratch/fisk/data/modis/stage/MCD43A4.A2012336.h12v04.006.2016112010833.hdf already in archive
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/391.schedtst.ags.io.SC", line 21, in <module>
    worker.fetch(u'modis', u'MCD43A4', u'h12v04', datetime.date(2012, 12, 1))
  File "/home/jfisk/datahandler/gips/gips/datahandler/worker.py", line 41, in fetch
    asset.name   = a_obj.archived_filename
AttributeError: 'modisAsset' object has no attribute 'archived_filename'
```

**Comment by ags-tolson** [comment]
Verified; I duplicated the error with this script:

https://gist.github.com/ags-tolson/ec26cfe56425be36e51a3a11c1e7e5d2

by "standard" modis assets I mean the ones needed for the system tests, but just one is sufficient.

**Comment by ags-tolson** [comment]
Fixed in PR #277

**Comment by ags-tolson** [comment]
Slight mission creep - going to look at products to confirm they don't have the same problem, will file an issue if they do.

**Comment by ags-tolson** [comment]
Looked at products, looks like same issue is possible; see issue #282.
