### ISSUE TITLE
inconsistent names and missing bands in data catalog

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#148]
The data catalog (DataVariable) has less than ideal names -- inconsistent capitalization, spaces, etc. 

And does not appear to include all bands.

This is what I got after gips_config

```
 id |                     name                      |                 description                  | driver |  product  |              band               | band_number 
----+-----------------------------------------------+----------------------------------------------+--------+-----------+---------------------------------+-------------
  1 | modis_fsnow_Fractional Snow Cover             | Fractional snow cover data                   | modis  | fsnow     | Fractional Snow Cover           |           0
  2 | modis_obstime_Observation Time Nighttime Aqua | MODIS Terra/Aqua overpass time               | modis  | obstime   | Observation Time Nighttime Aqua |           3
  3 | modis_landcover_landcover                     | MCD Annual Land Cover                        | modis  | landcover | landcover                       |           0
  4 | modis_quality_quality                         | MCD Product Quality                          | modis  | quality   | quality                         |           0
  5 | modis_temp8tn_temp8tn                         | Surface temperature: 1km                     | modis  | temp8tn   | temp8tn                         |           0
  6 | modis_clouds_Cloud Cover                      | Cloud Mask                                   | modis  | clouds    | Cloud Cover                     |           0
  7 | modis_temp_Temperature Best Quality           | Surface temperature data                     | modis  | temp      | Temperature Best Quality        |           4
  8 | modis_temp8td_temp8td                         | Surface temperature: 1km                     | modis  | temp8td   | temp8td                         |           0
  9 | modis_ndvi8_NIR                               | Normalized Difference Vegetation Index: 250m | modis  | ndvi8     | NIR                             |           1
 10 | modis_snow_Fractional Snow Cover              | Snow and ice cover data                      | modis  | snow      | Fractional Snow Cover           |           1
 11 | modis_indices_EVI                             | Land indices                                 | modis  | indices   | EVI                             |           5
```

**Comment by bhbraswell** [comment]
Agree, it's the band names. One thing I notice is that the band names for products that have just one band don't have the product name as the band name. i.e., row 1 should be modis_fsnow_fsnow and row 6 should be modis_clouds_clouds.

**Comment by ircwaves** [comment]
Though, I concur that the names are less than ideal, band descriptions are free form.  Having a band description that is redundant to the product name seems un-informative.  Maybe the data catalog name should be `datasource_product_band-number`?  Either that or maybe `band` should be a succinct-and-without-spaces name, and there should be an additional field describing the band in slightly more detail?

**Comment by bhbraswell** [comment]
I agree -- descriptions should be free and informative, and names should be succinct. I think @justinfisk 's original issue was the strings in the 3-tuple "name". I think the 3rd (band) element originally was just the number, and I'd be OK with it if it was just the number, but there was a good argument that it should be descriptive. Also something I didn't notice 

> And does not appear to include all bands.

I think it doesn't need to include all bands, just the ones we want to expose to geokit, right?

**Comment by remeryAGS** [comment]
The existing names were pulled from the modis.process function. I'm happy to camelCase them or replace them with something more suitable.

I've fixed the missing bands bug.
