### ISSUE TITLE
EarthData HTTP -> HTTPS

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#156]
On this Wednesday, NASA changed the protocol to https so my EarthData password will be super safe!

Task: replace http with https for all Earth Data data sets (MODIS, MERRA, Landsat). I verified that at least for MODIS this works.

**Comment by bhbraswell** [comment]
This is fixed in branch modis_trends
https://github.com/Applied-GeoSolutions/gips/tree/modis_trends

**Comment by ircwaves** [comment]
Via another route, this has made its way into `dev`.
