### ISSUE TITLE
rework inventory

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#16]
Inventory is the first thing GIPS does when it does anything. It performs a spatial comparison of all the user-specified features to identify the tile coverage, followed by a filesystem search to return a list of files matched with products, dates, and tiles. This is often really slow, and furthermore the results are only known and used internally to GIPS (except for a text dump to the screen). Proposed enhancement: do something awesome to make this faster and more useful.

**Comment by demiurg** [comment]
Choices for storing inventory so far:
https://dataset.readthedocs.org/en/latest/
https://github.com/otoolep/rqlite
https://github.com/coleifer/peewee - with django style settings for any DB

**Comment by ircwaves** [comment]
Is the choice of database driven by how we choose to enable asynchronous processing/concurrency for gips?

**Comment by bhbraswell** [comment]
I used SQLAlchemy for GIPS oceancolor. ORM very much like Django. Also why not Django?

Rob

**Comment by demiurg** [comment]
I think the choice is between apis and features needed for the coordination and performance of various operations, not just number crunching.

SQLAlchemy is great, but it has a lot of advanced stuff that might just be not necessary, and Django brings in a lot, too. Django might be interesting because it can make parts of gips easier reusable in a web site. Ultimately, the main point of the store is to be usable by multiple clients.

**Comment by bhbraswell** [comment]
I think a web interface whether GUI or API is where we’d like to go, at least for viewing inventory but probably for executing as well. So maybe Django would be a good choice.

**Comment by ircwaves** [comment]
@demiurg skrev:
> Ultimately, the main point of the store is to be usable by multiple clients

That sounds like a yes to me.

@bhbraswell skrev:
> ... but probably for executing as well ...

I suppose this is for a future GeoKit meeting, but I'm not sure what you mean by executing.

**Comment by bhbraswell** [comment]
I was thinking GIPS in general, not Geokit - my question is, if we want there to be GIPS services, then could django work for that? and if so, then django ORM might be a place to start with inventory.

**Comment by demiurg** [comment]
The main choice is not between ORMs but between data sharing systems and APIs they require.

**Comment by demiurg** [comment]
https://github.com/maxpert/LevelDBWinRT/wiki/Performance-And-Comparison

**Comment by demiurg** [comment]
Django was picked, and new design and prototype issue exists.
