### ISSUE TITLE
add date range and frequency to raster catalog

### ISSUE THREAD

**Issue by demiurg** [Applied-GeoSolutions/gips#168]

**Comment by ags-tolson** [comment]
When we extend the catalog for this, the source for this information is a class member of the asset classes, eg `gips.data.modis.modis.modisAsset._assets`:

https://github.com/Applied-GeoSolutions/gips/blob/dev/gips/data/modis/modis.py#L83

**Comment by remeryAGS** [comment]
The raster catalog only looks at the DataVariable model. Each instance may have multiple assets with different start dates. What is the correct way to handle this in the DataVariable model? List the oldest date?

**Comment by ircwaves** [comment]
Given our approach of only saying NO when there's no-way, I'd say use the
oldest date.

**Comment by justinfisk** [comment]
@remeryAGS 

after pulling these changes (from PR #258), we ran the migrations and loaded data variable catalog. It appears that `latency` was loaded, but not `start_date`.

Can you take a look?

**Comment by justinfisk** [comment]
PR #264 has addressed my concern. 

@demiurg is this resolved? or are we keeping this issue open to discuss further enhancement?

**Comment by demiurg** [comment]
Do most things have fixed "frequency"? This could be very useful, potentially.

**Comment by bhbraswell** [comment]
Yes most things have fixed frequency, but not all things.

Rob

**Comment by justinfisk** [comment]
@demiurg 

The issue with 
```
<Fault 1: "<type 'exceptions.TypeError'>:cannot marshal <type 'datetime.date'> objects">
```
has been solved in f097ef3 and deployed.

Issue is that xmlrpclib does not like `datetime.date` objects so have to convert to `datetime.datetime` before marshaling.

**Comment by ircwaves** [comment]
Looks like this potential fix is deployed, but Brandan notes that it isn't readable in JSON, with a 
```
<DateTime '20000224T00:00:00' at 7fe3dc552680> is not JSON serializable
```
And I note that it doesn't seem quite right in python either:
```
In [10]: import xmlrpclib

In [11]: cat = s.get_datacatalog()

In [12]: type([cat[i]['start_date'] for i in range(len(cat))][0])
Out[14]: instance

In [15]: str([cat[i]['start_date'] for i in range(len(cat))][0])
Out[15]: '20000224T00:00:00'
```

**Comment by remeryAGS** [comment]
Would it make sense to have xmlrpc use `datetime.datetime` instead of `xmlrpclib.DateTime`? It still needs to be handled in JavaScript but simplifies the python side.

**Comment by ags-tolson** [comment]
Another option if it's needed:  If all we care about is three small integers, is it easier to drop the instance types entirely and just do `{'year': y, 'mon': m, 'day': d}`?

**Comment by demiurg** [comment]
I think there is no need to invent a new date format. It should be either python datetime or a string. And it's datetime is fine now, it's being handled on the SB side.

**Comment by demiurg** [comment]
Also, I should note that if keys are used to store date/time ever, its better to use 'month' instead of 'mon', because that dict can be expanded into date constructor, which takes year, month, day arguments.

**Comment by bhbraswell** [comment]
If string, then I suggest ISO 8601 datetime string, e.g.

2017-05-02
or
2017-05-02T14:14:29

**Comment by ircwaves** [comment]
OK.  Well, at this hour, site-builder is handling this API quirk, and we should do nothing further here.  In the future, it may make sense to rev the API to use strings.  

@demiurg will relay to Brandan.

**Comment by ircwaves** [comment]
The raster catalog now presents a startdate with some quirks noted above.
