### ISSUE TITLE
fetch throttling

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#171]
Datahandler needs limit the number of jobs attempting to fetch simultaneously. 

Either allow only one fetch job to execute at a time, or better, one per data source.

**Comment by ircwaves** [comment]
done?

**Comment by ags-tolson** [comment]
I think yes?

https://github.com/Applied-GeoSolutions/gips/blob/batch-scheduler/gips/datahandler/scheduler.py#L57

**Comment by ircwaves** [comment]
Initial throttling done.
