### ISSUE TITLE
geokit api for data catalog

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#173]
Return relevant information from the data catalog (models.DataVariable) to the site builder. 

There is a stub for get_datacatalog() in the geokit_api.

**Comment by remeryAGS** [comment]
@demiurg Do you have any input on what you would like the return value to look like? I was thinking a list of dicts:
`[{'band': u'Fractional Snow Cover','band_number': 0,'description': u'Fractional snow cover data','driver':u'modis',u'id': 1,'name': u'modis_fsnow_Fractional Snow Cover','product': u'fsnow'},]`

**Comment by bhbraswell** [comment]
Yes. Also, units and a reference and/or link to relevant data center page for the asset e.g., https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd43a4_v006. Also time range and spatial extent.

**Comment by remeryAGS** [comment]
@bhbraswell Most of that information isn't even available in the driver. Should there be a separate issue to add it?

**Comment by bhbraswell** [comment]
I was just thinking a placeholder for now. Yes the driver is the place it would go. If we are just demonstrating with a few products then it shouldn't be hard to add units, for example all the MERRA product units are in comments.

**Comment by remeryAGS** [comment]
What form should time range and spatial extent take for database storage and JSON API output?

**Comment by demiurg** [comment]
Is it a good idea to return a list of ranges to represent holes?

**Comment by ircwaves** [comment]
I believe that the time range and spatial extent that @bhbraswell mentioned is more of a tuple of `(first_possible_date, last_possible_date)`.  

@bhbraswell is the spatial extent a short description, a single multi-polygon, or something else?

**Comment by bhbraswell** [comment]
Yes, for the catalog, I think that the time extent is a single date range. It's true that data gaps can exist within that range but that would be considered missing data.

I think the validation-related information in the catalog is not meant to be exhaustive but as a first-line check for requests that are not even possible. More detail than that would amount to having a second inventory of all data that we could possibly have.

I'll defer on the question of spatial extent, but I think a single multi polygon would work. So for MODIS indices, then all the tiles that have land could be merged. I'm not saying this is the highest priority, just something that would be useful and if it makes sense to have a place for it now, and create TODO issues then that might be good.

**Comment by demiurg** [comment]
a BBOX for spatial extent would also work in a similar fashion as a single date range

**Comment by ircwaves** [comment]
+ postponing spatial extent for now.
+ add asset documentation URL
+ add units (in `cfunits` format)
+ add category of measured quantity column (precipitation, temperature, reflectance, vegetation, snow)

**Comment by ircwaves** [comment]
@remeryAGS -- looks like there are a handful of items to be completed here (see my previous comment).  If you need pointers to the info for these items, @bhbraswell has you covered to the MAXX!

**Comment by bhbraswell** [comment]
Is there an updated proposed list of the minimum set of fields that need to be returned for all assets?

**Comment by ircwaves** [comment]
I don't know that we've got a list of fields.  Here's what we have at the moment:
```python
In [5]: pprint(cat[0])
{'asset': ['MOD10A1'],
 'asset_link': None,
 'band': 'cloud-cover',
 'band_number': 0,
 'category': None,
 'description': 'Cloud Mask',
 'driver': 'modis',
 'id': 9,
 'latency': 3,
 'name': 'modis_clouds_cloud-cover',
 'product': 'clouds',
 'start_date': <DateTime '20000224T00:00:00' at 7f12d8140878>,
 'unit': None}
```
so, `asset_link`, `category`, and `unit` are there, and just need to be filled out and/or extracted from drivers.

**Comment by remeryAGS** [comment]
Placeholders for category, unit, and asset documentation have been added to modis, merra, and daymet drivers (branch 173-driver-info)

**Comment by bhbraswell** [comment]
> Placeholders for category, unit, and asset documentation have been added to modis, merra, and daymet drivers (branch 173-driver-info)

So it's done then. I'll make a PR.

**Comment by ags-tolson** [comment]
geokit's been delivered and all the PRs mentioned here have merged, so I'm going to assume this need has been fulfilled.
