### ISSUE TITLE
MODIS driver

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#176]
This issue concerns primarily the EVI problem. The EVI problem was that MODIS indices product was not writing the EVI layer. Now it does. It also has a QC layer.

**Comment by bhbraswell** [comment]
See branch https://github.com/Applied-GeoSolutions/gips/tree/modis_trends

This works for me repeatedly and correctly:
```
rm -rf /data/gips/modis/tiles/h12v04/2007001
gips_inventory modis --rectify
gips_process modis -t h12v04 -d 2007-001 --fetch -v4
```

**Comment by ags-tolson** [comment]
See #186

**Comment by ircwaves** [comment]
#186 looks good....but we've gotta hotfix ndvi8 on master, so I'm going to split this up a bit.  Thanks, @ags-tolson .

**Comment by bhbraswell** [comment]
I think this issue can be closed, right?

**Comment by ags-tolson** [comment]
it looks like branch `modis_trends` has already been merged, so I'd say yes
