### ISSUE TITLE
landcover product is broken in modis

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#181]
This regular expression makes an assumption that is wrong for at least one asset type:

https://github.com/Applied-GeoSolutions/gips/blob/1540088a4efa5f22fbaa296a67cc71ecdbe7e48d/gips/data/modis/modis.py#L357

One asset type that breaks it is MCD12Q1 because its collection number is e.g. "051" which can't match `00(\d)`.

Reproduce the error with:

```
gips_process modis -s gips/test/NHseacoast.shp -d 2012-01-01,2012-01-01 -v 4
```

**Comment by ags-tolson** [comment]
Note that this product, since it apparently hasn't worked in some time, may get commented out before it gets fixed.

**Comment by bhbraswell** [comment]
I think that's fine, I could even do it.

**Comment by ags-tolson** [comment]
What the heck, this got fixed in January.
