### ISSUE TITLE
migrate to collection 6 for M*D10A1 

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#187]
Collection 5 and 6 differ significantly according to docs so a simple changing of URLs can't suffice:

http://modis-snow-ice.gsfc.nasa.gov/uploads/C6_MODIS_Snow_User_Guide.pdf

When the collection 6 URLS are put in for these assets, and 'snow' and 'fsnow' generation is attempted eg:

```
gips_process modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01 -v 4 -p fsnow --fetch
```

Then an assertion will fail and GIPS crashes:

https://github.com/Applied-GeoSolutions/gips/commit/d5cbbbb9a6ff4aab146738ae84e868397525faa3#diff-778716dbfdbf9e2055d9bb9a4f65c3d2R575

The assertion seems to fail because the code makes wrong guesses about what various important values, or even whole layers, might be.

**Comment by ircwaves** [comment]
This is addressed, and will be a part of the next release.
