### ISSUE TITLE
unnecessary(?) extra dimension when reading GeoImage to array

### ISSUE THREAD

**Issue by F-Sullivan** [Applied-GeoSolutions/gips#20]
when reading a multiband GeoImage to array with img.Read(), there is an extra dimension in the resulting array:

For example, this 80 band image:
>>> img = gippy.GeoImage(filename)
>>> arr = img.Read()
>>> arr.shape
(80, 1, 548, 4395)

This can be overcome with a numpy function ( arr = img.Read().squeeze() ), but seems an unnecessary step if there isn't a reason to have the extra dimension.

**Comment by ircwaves** [comment]
gippy has its own repo  (https://github.com/Applied-GeoSolutions/gippy), if there was a way to punt this over there, I would.

That said, I don't know the specific origin of this, but I've been squeezin' my numpy arrays for a long time.    It would be a good "nice to have" on that issue tracker.

**Comment by F-Sullivan** [comment]
I didn't even notice gippy...I clicked the first thing that started with "gip" - I'll see about moving this over...or removing it and opening an issue over there.
