### ISSUE TITLE
EarthData auth script from NASA

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#201]
NASA support guy told me to do it this way. Test script works for me at UNH.

https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python

**Comment by ircwaves** [comment]
Excellent!

**Comment by matthewhanson** [comment]
Interesting, this is way easier then how we are doing it:

https://github.com/AstroDigital/modis-ingestor/blob/develop/modispds/cmr.py#L65

As an aside, this is the MODIS ingestor, which AWS announced Tuesday at SatSummit:
https://aws.amazon.com/public-datasets/modis/

Not sure it's helpful to you guys at all. Note technically I'm still working on populating the data. I've got to add overviews and an index file(s), and we haven't yet started doing products other than MCD43A4 v006. 

This will be updating every night and we'll be backfilling it probably going back 5 years or so.

The TIF files are compressed and tiled to support windowed remote reads.

cc @stephenhagen @ircwaves @bhbraswell

**Comment by bhbraswell** [comment]
- [ ] aod
- [ ] cdl
- [ ] daymet
- [ ] landsat 
- [ ] merra
- [ ] modis
- [ ] prism
- [ ] sar
- [ ] sarannual
- [ ] sentinel2
- [ ] weld

**Comment by ircwaves** [comment]
A few notes:
+ don't have fetch: `sar sarannual cdl`
+ needs more overhaul: `landsat` (and being taken care of under another issue/project)
+ `prism` doesn't need auth, but migrating to a consistent fetch mechanism is probably good.

**Comment by bhbraswell** [comment]
The recommended method was implemented for modis by #240 , merged into batch-scheduler. Can I ignore this and proceed with working on this issue off of dev?

**Comment by bhbraswell** [comment]
Branch 201-earthdata enables the fix for this, implements it for merra.

@ircwaves please review at your convenience.

**Comment by bhbraswell** [comment]
Now addressed on branch 201-earthdata-dh (<-batch-scheduler). Also recently merged latest from dev.

**Comment by bhbraswell** [comment]
This does not work for NSIDC data, MOD10/ MYD10 assets (e.g. fsnow).

It's not clear why. I've tried enabling all Earthdata applications related to NSIDC.

I wrote to Earthdata help desk. They are usually helpful.

**Comment by bhbraswell** [comment]
> Dear
> 
>  Bobby, 
> 
> Thank you for reaching out to us regarding the MOD10* data download issues. We've made a few tweaks to the NASA-supplied Python script, and will contact Earthdata to see that it is updated. I have attached two scripts to this message. One will download a singular file, given the full URL all the way to the file extension. Additionally, there is a bulk download script attached as well. This will download all files within the **lowest** 'directory', but will not work recursively on lower directories. The URL supplied to the bulk script needs to end with a '/'.
> 
> Please let me know if you either of these solutions work for you and what problems you run into.
> 
> Regards,
> Greg
> 

watch this space

**Comment by bhbraswell** [comment]
To the best of my knowledge, branch [201-earthdata-dh](https://github.com/Applied-GeoSolutions/gips/tree/201-earthdata-dh) now fixes this problem. Different data centers apparently redirect in different ways.

**Comment by ags-tolson** [comment]
I dunno if comment edits notify people so here's an explicit comment:  there was uncertainty regarding weld, just to clear it up, it does earthdata login now, see commit 39081ef for working implementation.

**Comment by ags-tolson** [comment]
Also `201-earthdata-dh` but based on dev is in this branch:

https://github.com/Applied-GeoSolutions/gips/tree/201-earthdata-auth-fix

**Comment by ags-tolson** [comment]
Would like to prioritize this as I wasted about an hour rediscovering that weld fetch doesn't work right now, and getting about halfway through a fix before I remembered I already did it.  If 39081ef had merged by now, it would've been a non-issue.

**Comment by bhbraswell** [comment]
Is there something I need to do/ didn't do yet with this issue? It's been a while.

**Comment by ircwaves** [comment]
I don't believe so.  We'll discuss at the 1:30 meeting, but I believe that a PR wasn't created for 201.

**Comment by ags-tolson** [comment]
@bhbraswell Last thing I did, I believe, was give you a link to the replacement branch based off dev, which ircwaves had asked me to produce while discussing PR #276.  Link in case you don't have it handy:

https://github.com/Applied-GeoSolutions/gips/tree/201-earthdata-auth-fix

You can handle it from here however you want, but if it were me, since it's been a couple of months, I'd rebase to the current dev and retest before issuing a PR.  If you're too busy we can also assign this to someone else.

**Comment by ircwaves** [comment]
@ags-tolson please take this one, catch it up to `dev` branch, and PR it.
