### ISSUE TITLE
S2: Review the input required for 6S and update notes with this information (Ian).

### ISSUE THREAD

**Issue by stephenhagen** [Applied-GeoSolutions/gips#205]

**Comment by ircwaves** [comment]
@lledoux -- From my way-to-quick reading, are these good names for the MSI bands:

| wavelength (um) | name |
| --------- | -------- |
| 0.443 | COASTAL    |
| 0.490 | BLUE       |
| 0.560 | GREEN      |
| 0.665 | RED        |
| 0.705 | REDEDGE1   |
| 0.740 | REDEDGE2   |
| 0.783 | REDEDGE3   |
| 0.842 | REDEDGE4   |
| 0.865 | NIR        |
| 0.945 | WV         |
| 1.375 | CIRRUS     |
| 1.610 | SWIR1      |
| 2.190 | SWIR2      |

**Comment by lledoux** [comment]
I edited the table above (just the NIR and Red Edge 4 needed to be switched).

**Comment by ircwaves** [comment]
OK...too bad that MSI NIR is 23nm offset from the LC8 NIR.

**Comment by ircwaves** [comment]
MSIL1C algorithm: https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-1c/algorithm

Formula for reftoa-to-radtoa:

     RADTOA = REFTOA ·d(t)·E_S ·cos(θ_S ) / π

> where RADTOA is the TOA radiance, REFTOA is the TOA reflectance, t is the Julian day, d(t) is a correction to take the sun- Earth distance variation into account, E_S is the equivalent extra-terrestrial solar spectrum and depends on the spectral response of the Sentinel-2 MSI bands and θ_S : is the zenith angle (ESA, 2016). This was done for bands 2, 3, 4, 5, 6, 7,8a,11,12. Bands 1, 9, 10 were excluded since they are atmospheric bands designed for aerosol, water vapor, cirrus clouds.

**Comment by ircwaves** [comment]
info has migrated into the Sentinel-2 driver.
