### ISSUE TITLE
S2: Add `toa` based products

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#208]
`toa` product should be derived from the images within the SAFE.zip archive.  See https://github.com/Applied-GeoSolutions/gips/blob/200-sentinel2-driver/gips/data/landsat/landsat.py#L918

as an example of how to setup the raw files in the archive in a GeoImage, to then generate the desired products.

**Comment by ags-tolson** [comment]
Okay, I should be able to start on that today (doing the `--new-expectations` option presently)

**Comment by ircwaves** [comment]
#214 is sort of the first step of this issue.

**Comment by ags-tolson** [comment]
ref-toa and toa indices just merged in #220; what other TOA products are required for this issue?

**Comment by ircwaves** [comment]
I think that which has been added covers it for now.  Refinements and tweaks will eventually come down the 'pike.
