### ISSUE TITLE
Sentinel2: requesting NDVI, MTCI and S2REP indices

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/gips#213]
I have been using the following indices in my projects from Sentinel 2:

MTCI (MERIS Terrestrial Chlorophyll Index) = (Red Edge 2 - Red Edge 1 )/(Red Edge 1 -  Red)

NDVI (Normalized Difference Vegetation Index) = (NIR - Red)/(NIR + Red)

S2REP (Sentinel 2 Red Edge Position) = 705 + 35  ((((NIR + Red)/2) - Red Edge 1)/(Red Edge 2 - Red Edge 1))
 
in addition to the reflectance products of the red edge bands (all 4)

**Comment by ircwaves** [comment]
Good news is that `ndvi-toa` is already under way.  Other indices shouldn't be to bad to add.  Thanks.

**Comment by ags-tolson** [comment]
CF #200

**Comment by ags-tolson** [comment]
NDVI-toa and a ref-toa merged in PR #220 just now; rest of those indices will need to wait as current ref-toa doesn't have the four red edge bands.

**Comment by ircwaves** [comment]
@lledoux are these still needed?  is there an AGS project urgency?  Let's discuss offline.

**Comment by lledoux** [comment]
I actually do need the MTCI and S2REP products

**Comment by ircwaves** [comment]
Looks like MTCI has a very long-tailed bimodal distribution.  @lledoux let me know if that makes sense to you. 
![2017-10-23-094029_789x593_scrot](https://user-images.githubusercontent.com/9936909/31892254-919d7f98-b7d6-11e7-8d58-9a1d0f832367.png)

**Comment by lledoux** [comment]
This is the histogram that I've seen with an MTCI image that I had created a few months ago.


![histo](https://user-images.githubusercontent.com/16612231/31897891-ac890b24-b7e5-11e7-871b-421134fe3f6f.png)

**Comment by ircwaves** [comment]
Can you provide the tile and date there?  The values look suspicious, since
the end result should be in the neighborhood of (-1, 1).

**Comment by bhbraswell** [comment]
They'd be alright divided by 10

**Comment by ircwaves** [comment]
Right.  There is a range; and a quantization concern.

**Comment by lledoux** [comment]
The image is a composite of 4 different tiles, and the date is sometime in July of 2016.  Sorry, I can't find the exact day at the moment...

**Comment by lledoux** [comment]
and regarding range of values- I found this- [mtci](https://www.neodaas.ac.uk/supportedscience/veg_indices.php)

**Comment by bhbraswell** [comment]
Oh. the observed range is probably ok then.

**Comment by ircwaves** [comment]
From the [reference:](https://www.neodaas.ac.uk/supportedscience/veg_indices.php)
>  MERIS TOA/BOA vegetation indices
Meris Global Vegetation Index (MGVI) is the MERIS Top Of Atmosphere (TOA) Vegetation Index and can be used to assess the presence on the ground of green vegetation. The MGVI Level 2 product is calculated using three MERIS bands (blue/red/near infrared) and corresponds to the Fraction of Absorbed Photosynthetically Active Radiation (FAPAR). It has a practical range of 0 to 1.
> 
> https://www.neodaas.ac.uk/supportedscience/veg_indices.phpMeris Terrestrial Chlorophyll Index (MTCI) is the MERIS Bottom Of Atmosphere (BOA) Vegetation Index and can be used to determine the physiological status of the vegetation. The MTCI L2 product is calculated using three red/near infrared bands of Envisat MERIS data and represents the amount of chlorophyll per unit area of ground which is related to the photosynthetic rate. It does not have a theoretical maximum value, but practical values range from 0 to about 4.2.

**Comment by ircwaves** [comment]
@lledoux does the composite that you pulled that histogram on appear overly quantized?

**Comment by bhbraswell** [comment]
or, were there very few pixels in the image?

**Comment by ircwaves** [comment]
qgis doesn't normalize the histograms, so it appears to have 100,000s of pixels.

**Comment by lledoux** [comment]
Right.  There were quite a few small clouds, but enough valid pixels to be okay.  Overly quantized, how could I tell that?

**Comment by ircwaves** [comment]
The image would appear blocky.    If you took 
```
numpy.unique(img[0].Read(img.Chunks(numchunks=1000)))
```
you'd only get a few integer values.  The 1-d signal analogy is below.  Does that make sense?

![quantized sin wave](https://upload.wikimedia.org/wikipedia/commons/b/b1/2-bit_resolution_analog_comparison.png)

**Comment by lledoux** [comment]
The image does not appear overly blocky, and for some reason the above code snippet doesn't want to work for me.  If you'd like, the image is here: 
```
/projects/ForestDisturbance/gypsy_moths/classification/sentinel_2/GM_2016_S2_MTCI_nodata.tif 
```

**Comment by ircwaves** [comment]
That's the trouble with coding from memory on the fly, I forgot `[0]`:
```
In [11]: numpy.unique(img[0].Read(img.Chunks(numchunks=10)[0]))
Out[11]: 
array([-32768.        ,  -2225.96240234,  -1623.97241211, ...,
         1809.96948242,   1872.96838379,   2084.96459961], dtype=float32)

In [12]: vals = numpy.unique(img[0].Read(img.Chunks(numchunks=10)[0]))

In [13]: len(vals)
Out[13]: 439752
```

**Comment by lledoux** [comment]
I know everyone is super busy- I just couldn't remember if this had been implemented or not in gips?

**Comment by lledoux** [comment]
So- part of the reason S2REP looks a little funky is because I copied down the equation incorrectly (or rather, I found it written more explicitly in a paper):
705 + 35 * ((((B7 + B4)/2) − B5)/(B6 − B5))  where the band designations are:


![s2_bands_wiki](https://user-images.githubusercontent.com/16612231/33333973-6ab3dde2-d436-11e7-87f7-15fe2c330e63.png)

**Comment by lledoux** [comment]
I know it's been a while... but is this something in gips that I can create (S2REP and MTCI for Sentinel2)? Or what would be the best way for me to calculate or create these?

**Comment by bhbraswell** [comment]
@lledoux please use https://gitlab.com/appliedgeosolutions/gips/issues/213

@ircwaves can we close this GH repo for comments?
