### ISSUE TITLE
sen2cor metadata for atmosphere

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#217]
does sen2cor add any metadata about atmospheric conditions to output?

**Comment by lledoux** [comment]
There is a metadata document in the following directory:
```
/projects/ForestDisturbance/gypsy_moths/Sentinel/S2/S2A_USER_PRD_MSIL2A_PDMC_20160727T223603_R011_V20160727T154829_20160727T154829.SAFE/
 ``` 

called "S2A_USER_MTD_SAFL2A_PDMC_20160727T223603_R011_V20160727T154829_20160727T154829.xml" 

I also found this in a Sen2Cor document:

> The AC  processing consists  of  a  set  of  four  different  subtasks, AOT,  WV  and  terrain 
retrieval  (optional  with  terrain  and  cirrus  correction), having  three  different  user  products 
as output: AOT and WV tables on pixel level and the BOA corrected reflectance images 
for all bands measured.

**Comment by ircwaves** [comment]
Thanks.
