### ISSUE TITLE
aod driver update for MODIS Collection 6

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#219]
@bhbraswell and @stephenhagen -- given the granularity of the data, it seems reasonable to drop our collection 5 assets once updated collection 6 AOD assets have been pulled down.  I think it might be doable to have them live side-by-side, but that seems like an unnecessary use-case.  Your thoughts?

**Comment by bhbraswell** [comment]
I believe that collection 5 can be removed.

**Comment by ircwaves** [comment]
With that I will push this to `dev`

**Comment by ircwaves** [comment]
Pushed to `dev`
