### ISSUE TITLE
change `gips_stats` delimiting

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#22]
Currently `gips_stats` outputs a space delimited file, with the following header (spaces shown as underscores)

```
date_min_max_mean_sd_skew_count
```

and then the rows are as follows

```
2014-185_0.0_1.21_0.161231_0.273364_2.02997_65.0_
```

The header thus indicates that there are 7 columns, but the trailing space on the rows indicates that there are 8 columns, and pandas interprets this as the first data column is an index (`2014-185`), and shifts all the data so that `count == NaN`.

Reading in this in pandas requires using arbitrary number of whitespace delimiting (`r'\s+'`).  It would be more simple if that trailing space was omitted, or if TABs or commas were used for delimiters.

**Comment by bhbraswell** [comment]
Yeah. I recommend semi-standard csv, no spaces anywhere unless they are literal, in which case quotations can be used.

name,date,min,max,mean,sd,skew,count
bob,2014-185,0.0,1.21,0.161231,0.273364,2.02997,65.0
“ian cooke”,2014-185,0.0,1.21,0.161231,0.273364,2.02997,65.0

**Comment by mcorbiere** [comment]
Might be helpful to note issue #7 here if someone is going to be editing the way the stats files are created.
