### ISSUE TITLE
Data handler missing values in some geometries

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#227]
As seen in the geokit demo, some locations are either returned with missing values or are not returned.

**Comment by ircwaves** [comment]
@justinfisk -- did you say that you were going to have time to look into this one?

**Comment by bhbraswell** [comment]
The underlying problem here is described in #229 right?

**Comment by ircwaves** [comment]
I believe #229 will address the small polygons being missed, but the other component is #231.  Once both of those are fixed, this should sublimate.

**Comment by justinfisk** [comment]
Solved with #241.
