### ISSUE TITLE
DH resolution and alltouch issue

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#229]
Currently, DH has an issue with geometries smaller than a product pixel (e.g. small counties and merra data). I put a partial solution in place to support the existing 'alltouch' option, but I don't believe it will work correctly.

Some thoughts:

 * alltouch needs to have a resolution specified  
 * Geokit user doesn't want to know anything about resolution. 
 * data catalog could be extended to know the product resolution 
 * incoming shapefiles could be reprojected to match the requested products resolution

My partial solution is not yet merged into the batch-scheduler branch, but exists in the batch-scheduler-better-tracking branch. It pulls the resolution from the first file it gets from the inventory, but that resolution may not be in the same units as the shapefile.

**Comment by bhbraswell** [comment]
@ircwaves to summarize our discussion yesterday I think we decided that there are two options

- DH behaves like gips_project and requires --res so any client (e.g. SB) will have to figure out what res to specify. This in turn means that DH should be able to provide the resolution on a product basis on request

- In the absence of --res, DH figures out a reasonable default behavior on its own. This would work only if the requested location geometries are projected (i.e. in meters). If the shapefile is in WGS84, then it wouldn't be clear what to do in this option.

Did I get that right?

**Comment by ircwaves** [comment]
That's jives with my memory.

In terms of WGS84 shapefiles, I feel like we could do

    A. some complicated triage of the shapefile to figure out which a projection to use
    B. Go Gall-Peters!
    C. or just error.

**Comment by bhbraswell** [comment]
ha ha Gall Peters. We might be stuck with C first, then try to do A.

**Comment by demiurg** [comment]
Is this a lack of a feature in the gippy code?

**Comment by bhbraswell** [comment]
> Is this a lack of a feature in the gippy code?

No, this is because when gips is creating project (mosaicked/ clipped) export files, it uses the SRS of the requested locations and, usually, a specified output resolution using `--res xres yres`

Because the geokit admin shouldn't need to care about the resolution of the rasters, we are trying to figure out how to tell gips a resolution without bothering the client. Alternatively, as mentioned above, geokit has to know what res to use.

**Comment by demiurg** [comment]
Since raster products are not being combined, does it not make sense to reproject the vectors to raster projection?

**Comment by bhbraswell** [comment]
Yes, except that the raster might not have a single projection, e.g. a request for Landsat data that crosses Path/Row boundaries. But yes, something like this is probably the way to go.

**Comment by bhbraswell** [comment]
very sneaky, putting stuff in `gips/inventory/orm/__init__.py`

**Comment by ags-tolson** [comment]
You should look at `gips/inventory/__init__.py`.  Seriously though I'm not sure how unconventional it is to put code in `__init__.py` files so I'm willing to refactor that to be more normal if people want.

**Comment by demiurg** [comment]
its very unconventional, init should have module import hacks mostly

**Comment by bhbraswell** [comment]
once I know there might be code in there, then I'm all set.

**Comment by bhbraswell** [comment]
@justinfisk I'm ready for an example shapefile that didn't work, i.e. that resulted in missing features in the aggregation summary.

**Comment by bhbraswell** [comment]
Shouldn't the scripts, e.g. gips_project, use the API? That way if we wanted to for example set a default for something, we'd know where to put it, and we'd only have to put it in one place?

**Comment by bhbraswell** [comment]
Also what is the most effective way for me to complain in a constructive way about the use of **kwargs?

**Comment by bhbraswell** [comment]
Found this in `gips/tiles.py`

```
           if not os.path.exists(fout) or overwrite:                                                                                                         
                with utils.error_handler("Error mosaicking " + fout, continuable=True):                                                                       
                    filenames = [self.tiles[t].filenames[(sensor, product)] for t in self.tiles]                                                              
                    images = gippy.GeoImages(filenames)                                                                                                       
                    """                                                                                                                                       
                    if alltouch and res is None:                                                                                                              
                        timg = gippy.GeoImage(filenames[0])                                                                                                   
                        res = []                                                                                                                              
                        res[0] = abs(timg.Affine()[1])                                                                                                        
                        res[1] = abs(timg.Affine()[5])                                                                                                        
                    """                                                                                                                                       
                                                                                                                                                              
```

Someone has been here before...

**Comment by justinfisk** [comment]
Yes, that was my first half-baked attempt at resolving this. Backed out because of resolution unit mismatch issues

**Comment by bhbraswell** [comment]
I feel like I have passed the first part of your test.

**Comment by justinfisk** [comment]
@bhbraswell I sent you a shapefile through other channels. It is somewhat large (created for the southern states in the use-case), but has a number of examples of the error. Here are the shaids for a few:
```
4e595ef278af27568093149f29da1e61612635a4
6eeccaafa78719e57ff72208bed3e6bcc958fbac
58483d4c538aee7dd06e156cda77a9f77899d0fa
f1ad96072417227a29f0cd4dfd2ec68b88a7c65a
```

The error generated is this:
```
(256, 'ERROR 1: Attempt to create 1x0 dataset is illegal,sizes must be larger than zero.\nCreation failed, terminating gdal_merge.')
```

**Comment by justinfisk** [comment]
Also worth noting:

Currently that error does not trigger any kind of job failure. It just skips over the offending geometry. The errors are buried in sub-task output files and don't percolate up to anywhere useful to alert anyone of the issue. At a minimum, it should at least report something to the central log.

**Comment by bhbraswell** [comment]
![img_3042](https://cloud.githubusercontent.com/assets/3209308/24669129/3000f30c-1937-11e7-8385-5647ffe19900.JPG)

**Comment by ags-tolson** [comment]
(note that if you click on that image it appears with the correct orientation . . . weirdly)

**Comment by ircwaves** [comment]
Beautiful, @bhbraswell !

**Comment by bhbraswell** [comment]
Factorial use cases:

1. Raster data are (a) geographic or (b) projected
2. Requested locations are (a) geographic or (b) projected
3. Resolution is (a) specified; (b) not specified
4. Alltouch is (a) true; (b) false

I believe there is a scientific or technical rationale for supporting all of these choices, but should all the combinations be allowed? This probably depends on what is the reason for making the choice, but even this can be complicated - for example, did I not specify resolution because I don't know it, or because I want the result to not be warped? Does it matter? If the user (e.g. geokit) wants a spatial aggregation, should they just know that they should be using locations that are projected?

What isn't clear to me is where the bug is - but presumably the problem is that the "no res" option doesn't support "alltouch" because it uses gdal_merge instead of CookieCutter.

**Comment by bhbraswell** [comment]
My test case has two features, one that succeeds and one that fails with MERRA, which is 0.625 x 0.5 degrees.

Extent bounds for feature 1 (succeeds) are:
dx = 0.435733
dy = -0.308495

Extent bounds for feature 2 (fails) are:
dx = 0.227459
dy = -0.312229

Feature two is smaller, sure, but neither are larger than 0.625 x 0.5. Just sayin.

**Comment by ircwaves** [comment]
does the merge of #241 resolve this issue?

**Comment by bhbraswell** [comment]
I suggest verifying independently with the original test shape file (counties).

**Comment by bhbraswell** [comment]
Does this need to stay open until batch scheduler merges?

**Comment by ags-tolson** [comment]
We seem to be closing DH issues as they merge into the BS branch; #234 & #216 are good examples.

**Comment by bhbraswell** [comment]
One down 99 to go

**Comment by ags-tolson** [comment]
![99 bugs](https://res.cloudinary.com/teepublic/image/private/s--jcRL641O--/t_Preview/b_rgb:42332c,c_limit,f_jpg,h_630,q_90,w_630/v1475762150/production/designs/717061_1.jpg)

**Comment by justinfisk** [comment]
we intended to test this against the counties shape file to make sure everything worked. i ran the test, but did not verify that all geometries were in the results table yet

**Comment by justinfisk** [comment]
I have re-run a 1-year test using the original counties shape file that was causing the problem. All is well. Closing this and #227

**Comment by bhbraswell** [comment]
(-:
