### ISSUE TITLE
gips_archive failing where it had once succeeded

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#23]
While trying to test a new Landsat asset (more on that later), we found that gips_archive is not moving a L8 file that had been temporarily been taken from the archive. That file had at some point been placed in the archive by gips_archive. So don't know what is up. Permissions problem?

```
(venv)rbraswell@rio:/titan/data/landsat/stage/rbraswell$ ls -l
total 1307648
drwxrwxr-x 2 rbraswell staff      3896 Jan  7 10:22 copy
-rwxr--r-- 1 mcorbier  staff 942899994 Aug 31 11:34 LC80120292015240LGN00.tar.gz
-rw-rw-r-- 1 rbraswell staff 396030814 Nov  9 08:17 LC81190622014027-SC20151105030019.tar.gz
(venv)rbraswell@rio:/titan/data/landsat/stage/rbraswell$ gips_archive landsat 
GIPS Data Archive Utility (v0.8.1)
Data archive error: Problem adding ./LC80120292015240LGN00.tar.gz to archive: [Errno 1] Operation not permitted
```

**Comment by ircwaves** [comment]
That is a permissions issue.   `rbraswell` doesn't have write permission on that file.  If you run `gips_archive` with `--keep`, then it should work.  Or if `mcorbier` grants you write permissions on the file:
```
mcorbier@rio:$ chmod g+w /titan/data/landsat/stage/rbraswell/LC80120292015240LGN00.tar.gz
```

**Comment by mcorbiere** [comment]
I changed the permissions

**Comment by ircwaves** [comment]
Seems done then...the oddity here was that Rob was able to move the file out of the archive (depends on directory permissions only), but then the delete that `gips_archive` does could not be done because he did not have write permission the file itself (depends on file permissions only).
