### ISSUE TITLE
DH post-processing failures are too coarse

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#231]
Export and aggregate tasks are submitted as small batches of geometries. If one geometry fails, then all remaining geometries in that task fail. It should catch the exception and process the rest.

**Comment by ircwaves** [comment]
are they submitted with intra-job dependencies?  If so, maybe just getting rid of the dependency will do the trick?

**Comment by justinfisk** [comment]
No. Each torque job does a small handful of geometries. I was trying to avoid overhead of launching zillions of torque jobs.

**Comment by ags-tolson** [comment]
per discussion this isn't a priority for now
