### ISSUE TITLE
DH include non-torque task scheduler

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#234]
GIPS batch-scheduler branch currently supports torque but for sharing with a broader audience we need something more lightweight, e.g. Celery or RQ. Geokit site builder uses RQ, so we should use that if possible. 

1 - Investigate whether RQ features are sufficient, if not check out Celery

2 - Implement this next to the torque code and add a switch with the default set to the non-torque options

I think eventually the simpler option should be deployable, right?

**Comment by demiurg** [comment]
RQ is so simple, it can be considered a subset of other async queues. So, if it's possible to create RQ workers, they would be easily portable to many libraries.

**Comment by bhbraswell** [comment]
That's one important piece of information, the other is whether RQ has the minimum features needed by DH.

**Comment by ags-tolson** [comment]
Present plan based on meeting with @ircwaves and @justinfisk:

```
initial iteration
-----------------
mostly work off a subbranch(es) of batch-scheduler
    frequent merges into batch-scheduler
only one RQ queue
keep cron job that organizes the work, and the task tracking in the inventory ORM
add datahandler/rq.py to be an analog of datahandler/torque.py
add just enough config & settings to let:
    the cronjob scheduler talk to an rq worker via a running redis
    let the user configure either torque or RQ
march through torque.py and duplicate it, task by task
```

**Comment by ags-tolson** [comment]
Tentative design:  A new setting, `TASK_QUEUE`, can be either 'torque' or 'rq'.  `scheduler.py` et al will call `datahandler.queue.submit(...)` which will route the call to the configured task backend.  File layout:

```
datahandler/torque.py # moved into queue/
datahandler/queue/
    __init__.py # has `from .queue import *` for convenient use mostly by scheduler
    torque.py   # mostly unchanged from current code
    rq.py       # like torque.py but for RQ (obviously)
    queue.py    # has `submit(...)` as its major call offered to the rest of the DH
```

I'm going to set it up so that `rq.py` isn't imported unless it's needed for a call, so that you don't have to have rq installed to run the datahandler.

**Comment by ags-tolson** [comment]
A more detailed dev plan is as follows, so people can keep track of my progress:

- [ ] move files into new layout, and change callers from `torque.submit` to `queue.submit`.  Deliverable:  Torque jobs still work when `TASK_QUEUE == 'torque'`.
- [ ] `touch queue/rq.py` and make it talk to Redis & the RQ worker.  Deliverable:  A faked-out DH function runs in the RQ worker.

Here down it's building up the calls; the deliverable in each case is the call being serviced by the worker daemon:
- [ ] query
- [ ] fetch
- [ ] process
- [ ] export-and-aggregate

**Comment by ags-tolson** [comment]
Also, I'm assuming deployment is out of scope for this issue.

**Comment by bhbraswell** [comment]
> Also, I'm assuming deployment is out of scope for this issue.

@ags-tolson can you say what you mean by that? Do you mean deployment of RQ or Torque?

**Comment by ags-tolson** [comment]
Sure @bhbraswell - In other words, I'm assuming that deployment automation (with an ansible playbook) or deployment itself (by tinkering as root someplace) will be separate issues.

**Comment by ags-tolson** [comment]
PR submitted to finish this issue:  https://github.com/Applied-GeoSolutions/gips/pull/248

**Comment by ags-tolson** [comment]
#248 merged so this iteration of RQ support is complete
