### ISSUE TITLE
some modis providers are ignoring HTTP auth

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#238]
Right now this command doesn't work, even though it worked a few days ago, and the error reported by gips isn't useful becaues the provider isn't providing a useful HTTP response I don't think (this is the dev branch gips):

```
(.venv) laptop2:~/src/gips$ GIPS_ORM=false gips_inventory modis --fetch -d 2013-001,2013-003 -p fsnow -t h12v04 -v6
GIPS Data Inventory (v0.8.2)
Retrieving inventory for site tiles
Unable to find remote match for (MYD10A1.A2013001.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOSA/MYD10A1.005//2013.01.01
Unable to find remote match for (MYD10A1.A2013002.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOSA/MYD10A1.005//2013.01.02
Unable to find remote match for (MYD10A1.A2013003.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOSA/MYD10A1.005//2013.01.03
Unable to find remote match for (MOD10A1.A2013001.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOST/MOD10A1.005//2013.01.01
Unable to find remote match for (MOD10A1.A2013002.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOST/MOD10A1.005//2013.01.02
Unable to find remote match for (MOD10A1.A2013003.h12v04.\d{3}.\d{13}.hdf) at https://n5eil01u.ecs.nsidc.org/MOST/MOD10A1.005//2013.01.03
```

The response for all those URLs, examined in the debugger, seems to be a login page.  I then visited one of the URLs in firefox and tried my credentials in the login page, which worked.  So it's acting like it's silently ignoring HTTP auth, and requiring users to submit formdata (or ajax or something) instead.

Since it's Wednesday, I'm filing an issue to remind myself to check again tomorrow for confirmation.  Also I'm pretty sure it started breaking last night, which was Tuesday.

**Comment by bhbraswell** [comment]
If this happens on a not-wednesday I suggest reporting it to the help desk at the data center, they seem to be fairly responsive.

**Comment by ags-tolson** [comment]
sounds good @bhbraswell will do.  For tomorrow's check, I'll use the invocation that our fetch test does:

`gips_inventory modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-01 -v 4 --fetch`

**Comment by ircwaves** [comment]
Was this occurring yesterday (aka not-wednesday)?

Do you have a `~/.netrc` file in place?

**Comment by ags-tolson** [comment]
Yes, I think it was the same error yesterday evening, but at the time I hadn't found the root cause.  The same fetch worked a little while before that, late last week I believe, on my local dev gips.

I have no `~/.netrc` file on my local machine, nor on my home dirs in the torque clusters.

**Comment by ircwaves** [comment]
You need a `~/.netrc` file until #201 is resolved.

**Comment by ags-tolson** [comment]
Okay; I'm calling it a duplicate of #201 then.
