### ISSUE TITLE
rectify can leave assets in the 'requested' state even if they exist

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#239]
If the DB contains an asset in the 'requested' status, and the asset exists on the filesystem, rectify appears to leave the DB record as 'requested'. Should update to 'complete'.

**Comment by ags-tolson** [comment]
fix is in #255; while I was in the rectify code I found other problems; issues forthcoming

**Comment by ags-tolson** [comment]
I forgot to close this, sorry
