### ISSUE TITLE
Move contents of requirements.txt into setup.py

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#245]
Use requirements files for building specific environments for specific purposes, not package dependency management (mea culpa - I reintroduced requirements files when some of their current content should've gotten into `setup.py:setup(install_requires=(...))` instead.  Basically requirements should be for deployment, while `setup.py` is for packaging.

Also use `setup(extras_require={...})` for optional packages such as packages needed for specific drivers, thus users only interested in modis won't have to install packages needed only for landsat.  This is also handy for datahandler stuff such as RQ vs. torque vs. no datahandling at all.

More info:  https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by ags-tolson** [comment]
A stash I had for working on this, contains a start:

https://gist.github.com/ags-tolson/9f60055d9a5662c13ed097c03cd3f0f0

**Comment by ircwaves** [comment]
This is done in the datahandler branch as of d650a3f.
