### ISSUE TITLE
remove dependency links from setup.py

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#246]
Stop relying on dependency links in `setup.py` as this (apparent) misfeature won't be supported by pip `--process-dependency-links` indefinitely.

**Comment by ircwaves** [comment]
There's a bit of confusion around this, but the most recent information that I have regarding `--process-dependency-links` is here:
https://github.com/pypa/pip/issues/4187

**Comment by ags-tolson** [comment]
My mistake:  It's an apparent misfeature in setuptools but only deprecated in pip; I've edited the top comment accordingly.

I say 'apparenty misfeature' because this guy thinks so, and he's evidently a significant contributor to the python software landscape; here's the blog post I found earlier and put into another of our packaging issues:

https://caremad.io/posts/2013/07/setup-vs-requirement/ <-- section "A Setuptools Misfeature"

The author of that, by amazing coincidence, wrote the relevant comment here:

https://github.com/pypa/pip/pull/1955#issuecomment-50973856

That issue, 1955, is the one linked by pypa/pip#4187!  :astonished:

**Comment by ircwaves** [comment]
We will only continue to use this misfeature until gippy 0.3.x is updated at the cheese shop OR we migrate to gippy 1.x.
