### ISSUE TITLE
Make `daymet` ORM-compatible

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#251]
`busted_drivers` is in the `gips.inventory.orm.setup` function (in `gips.inventory.orm.__init__.py`).

**Comment by ircwaves** [comment]
@bhbraswell -- question to go along with this: Should we archive the Version 2 products we currently have?

Also, to whomever takes this issue, before removing daymet from busted drivers:
- [ ] add metadata indicating which daymet version (or URL) the dayment products were derived from
- [ ] add metadata indicating the daymet driver version.  

These will help with provenance and data management.

**Comment by bhbraswell** [comment]
I believe the only reason we might need to archive expired data is for reproducibility of a published result. I don't have anything for this data but we should open it up to the larger group.

**Comment by ircwaves** [comment]
Need to file RRF.

**Comment by ags-tolson** [comment]
That PR, #321, does what this issue says, namely ORM compat & adding basic metadata to the asset/product files; once that merges I think this can close.
