### ISSUE TITLE
gips_project Landsat

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/gips#26]
I am trying to gips_project Landsat on nile, I have also tried rio, and am receiving this error:

lledoux@nile:/titan/data/landsat/stage/lindsay$ gips_project Landsat -s /titan/data/landsat/stage/lindsay/shapefiles/Central_kalimantan.shp -d 2013-01-01,2015-12-31 --sensors LC8 -p acca ref-toa evi ndvi --outdir /titan/data/landsat/stage/lindsay/Central_Kal/ --suffix _centralk --tree --crop
GIPS Data Project (v0.8.0rc4)
Data Project error: DataInventory: Error accessing tiles in Landsat repository

Any suggestions?

**Comment by bhbraswell** [comment]
To help diagnose the problem can you try a different date, or a different area? Maybe use -t [tile] instead of a shapefile, then look in the archive and see if everything is there and permissions are OK.

**Comment by ircwaves** [comment]
That would be a good first step at narrowing the scope of the problem.
As always...makes a point that issue #8 needs addressing.

++ Ian

**Comment by lledoux** [comment]
So I just tried:
lledoux@nile:/titan/data/landsat/stage/lindsay$ gips_project Landsat -s /titan/data/landsat/stage/lindsay/shapefiles/East_kalimantan.shp -d 2013-01-01,2015-12-31 --sensors LC8 -p acca ref-toa evi ndvi --outdir /titan/data/landsat/stage/lindsay/East_Kal/ --suffix _eastk --tree --crop
 
in other words, changing the shapefile, and it seems to be working...

**Comment by bhbraswell** [comment]
Maybe try just one date, with the shapefile, and check permissions and files for all the relevant tiles.

Rob

**Comment by ircwaves** [comment]
I think this confirms that it is due to the duplicate asset:
```
icooke@nile:~$ gips_inventory Landsat -t 120061 -d 2015-149 -v4
GIPS Data Inventory (v0.8.0rc4)
Retrieving inventory for site tiles
/titan/data/landsat/tiles/120061/2015149/LC81200612015149LGN00.tar.gz
/titan/data/landsat/tiles/120061/2015149/LC81200612015149-SC20151121043437.tar.gz
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gips/scripts/inventory.py", line 49, in main
    inv = DataInventory(cls, extent, TemporalExtent(args.dates, args.days), **vars(args))
  File "build/bdist.linux-x86_64/egg/gips/inventory.py", line 242, in __init__
    raise Exception('DataInventory: Error accessing tiles in %s repository' % dataclass.name)
Exception: DataInventory: Error accessing tiles in Landsat repository

Data inventory error: DataInventory: Error accessing tiles in Landsat repository
icooke@nile:~$ 
```
move those files out of the repo and:
```
icooke@nile:~$ mv /titan/data/landsat/tiles/120061/2015149/120061_2015149_LC8SR_ndvi8sr.tif /titan/data/landsat/stage/rbraswell/
icooke@nile:~$ gips_inventory Landsat -t 120061 -d 2015-149 -v4
GIPS Data Inventory (v0.8.0rc4)
Retrieving inventory for site tiles

Asset Holdings
    DATE     Coverage  Product  
2015        
    149       100.0%     lswi  ndti  ndvi  ref  satvi  tcap


1 files on 1 dates

SENSORS
LC8: Landsat 8
LE7: Landsat 7
LT5: Landsat 5
icooke@nile:~$ 
```

**Comment by ircwaves** [comment]
@lledoux : Can you re-run with that shapefile and close this issue if it runs w/o issue.  Thanks

**Comment by lledoux** [comment]
I am running (successfully) gips_project with the original shapefile that had previously not worked.  Thank you!
