### ISSUE TITLE
record system test results for geokit here

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#278]
Run automated tests and attach log of the results here for 
1) MODIS
2) MERRA
and if there's time
3) daymet

**Comment by ags-tolson** [comment]
MERRA and MODIS transcripts are saved here:

https://drive.google.com/drive/folders/0B54rUezkgWNPdlNaX3hMYmdoN1E?usp=sharing

**Comment by bhbraswell** [comment]
Should these logs be included in the release?

**Comment by ags-tolson** [comment]
I guess they'd be good appendix material; sorry for late reply in any case.
