### ISSUE TITLE
dh jobs with `failed` assets or products should be marked as `failed`

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#286]
In `schedule_export_and_aggregate` we check to see if any post-processing steps have failed and if so mark the job as `failed`, but we don't check for failures in previous steps. 

It is already getting the status of all product dependencies, so it should be fairly straight forward to fix. 

It might be best to have `schedule_process` check for products with `failed` asset dependencies and  mark the product as `failed` as well.

**Comment by ags-tolson** [comment]
Fix in PR #292

**Comment by ags-tolson** [comment]
PR was merged; I think this is done.
