### ISSUE TITLE
Replacement DH logging

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#290]
Set up a test task in RQ that does nothing but `print 'hello world from {jobid}'`.  Have it load default python logging (and not `gips.datahandler.logger`), but configured to talk to the existing dhd logging server.  Have it use a log named `__name__`.  Use these docs to save the job ID:

https://docs.python.org/2/howto/logging-cookbook.html#adding-contextual-information-to-your-logging-output

Have it also call code in another module that makes a logging call from elsewhere; write another throwaway function if needed.

Meanwhile, alter the logging server to differientiate based on log name, and print the job id for the above `__name__`, but not for otherwise.

The deliverable is a branch based on `datahandler` that demonstrates successful log messages both with and without the job ID; possibly write an automated test.

**Comment by ags-tolson** [comment]
I estimate about a day for this.

**Comment by ags-tolson** [comment]
So the needed approach turned out to be different but the goal is realized:  Job IDs get into log messages now, but when they're not available, it gracefully falls back to process ID.  filename is reported on log message so the scheduler, dhd, and workers can be differentiated.  Took longer than 1 day because django and RQ had unexpected interactions in their logging configs.

**Comment by ags-tolson** [comment]
see branch `logging-improvements`

**Comment by ircwaves** [comment]
fixed by #346
