### ISSUE TITLE
gips_project Landsat creating files of varying size

### ISSUE THREAD

**Issue by dchowdhury** [Applied-GeoSolutions/gips#30]
gips_project Landsat is creating project directory with files of varying size. The Y size is the same for all images, but X size changes. Problem seems to be limited to LT5 data in my case. See products in gips_project dir: 

/scratch/dchowdhury/RICE_DSS/Arkansas/tile_023035/AR_023035_30.0x30.0_Landsat/0/

**Comment by lledoux** [comment]
And when attempting to use Rob's band-aid for the varying file sizes (reshape_stack_like.py)  I get errors::

lledoux@nile:/atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0$ for i in *; do python /scratch/lledoux/cmsindo/Docs/reshape_stack_like.py /atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0/ /atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0/2013011/2013011_LE7_acca-1-20-3000.tif /atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0/; done
/atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0/2013011/2013011_LE7_acca-1-20-3000.tif
x 1976 1976 393260.394541 393260.394541 0.0 0.0
y 6961 6961 -214764.373341 -214764.373341 -0.0 0.0
/atlas/projects/cmsindo/data/landsat/logging/SouthKal/SouthKalimantan_utm50n_30.0x30.0_landsat/0/2013050/2013050_LE7_acca-1-20-3000.tif
x 1976 7706 393260.394541 221360.394541 -5730.0 0.0
y 6961 6951 -214764.373341 -215064.373341 10.0 0.0
trimming left
buffering top
Traceback (most recent call last):
  File "/scratch/lledoux/cmsindo/Docs/reshape_stack_like.py", line 92, in <module>
    run(startdir, pattern, refpath, outdir)
  File "/scratch/lledoux/cmsindo/Docs/reshape_stack_like.py", line 81, in run
    assert data.shape == (ny, nx)
AssertionError

**Comment by bhbraswell** [comment]
As you can see in the output from the script, some of the images are so different in dimension (by thousands of pixels) that they can’t be trimmed/ buffered in the stepwise manner that my code. I recommend addressing the underlying cause, at least for the files that Lindsay is pointing to.

BTW, if you want to work with, or debug, this “band-aid” script, please make your own copy. I just found and fixed one issue that might make a difference, at least in less extreme cases.

Rob

**Comment by ircwaves** [comment]
Based on the extremely different sizes, I asked Lindsay and Diya if they were using the `--crop` option, and they are.  This makes the output image size variable.  
```
especially if extent(shapefile).intersect(extent(image)) != extent(shapefile) 
```
For most analysis tasks, this is probably not useful.  Both are re-running their code w/o that switch.

**Comment by dchowdhury** [comment]
Comparing output of previous --crop and nocrop results looks like projection is off.

**Comment by ircwaves** [comment]
As Diya and I have discussed, the different sized outputs were a result of the use of the `--crop` option to `gips_project` which computes the minimum bounding box of the intersection of the image bounding box and the shapefile bounding box.  

To avert this confusion in the future, I have the usage string of `gips_project` to indicate this more clearly (be84ed9)
