### ISSUE TITLE
disseminate make_temp_dir context manager to drivers

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#304]
To eliminate a source of corrupt data in the GIPS archive, all drivers should use a temporary directory as a workspace for generating new products.

+ Base Requirements
    - [x] Work through processing steps in a tempdir in the driver's stage directory (s.t. moving into scene dir is efficient) 
    - [x] The last step of processing should be to move the product into the scene directory if-and-only-if it completes w/o error.
+ Drivers to cover (in rough descending order of importance):
    - [x] PRISM (for simplicity):  merged
    - [x] Sentinel-2:  PR #313
    - [x] MODIS:  PR #312
    - [x] MERRA:  PR #312
    - [x] Landsat:  PR #316
    - [x] Daymet:  PR #313
    - [x] aod:  apparently nothing to do
    - [x] WELD:  PR #313

**Comment by ircwaves** [comment]
method was created for #115 and now being extended to each of the above drivers.

**Comment by ags-tolson** [comment]
Test comment to see if I can check the boxes in my own comment, will edit shortly:

+ Drivers to cover
    - [ ] PRISM (for simplicity)
    - [ ] Sentinel-2
    - [ ] MODIS
    - [ ] MERRA
    - [ ] Landsat
    - [ ] Daymet
    - [ ] aod
    - [ ] WELD

**Comment by ags-tolson** [comment]
Last one merged, believed fixed.
