### ISSUE TITLE
prism assets aren't inventoried in the ORM

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#305]
To duplicate (caution, this clears the repo):
1. `GIPS_ORM=1 pytest -k 'prism and t_inventory' -s -vv --sys --ll debug --clear-repo # notice tests fail`
2. `GIPS_ORM=1 gips_inventory prism -v6 # nothing shows in inventory`
3. `GIPS_ORM=0 gips_inventory prims -v6 # but inventory looks correct with ORM turned off`

Inspecting the DB showed that there were no prism rows in dbinv_asset.  Rectify didn't add rows to that table either.  The system test asset download is done with this command:

`gips_inventory prism -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 1982-12-01,1982-12-03 -v 4 --fetch`

**Comment by ircwaves** [comment]
In discussion, this was determined to be a bug introduced in #297 by the regex pattern matching both the asset file and the associated `.index` file.

**Comment by ags-tolson** [comment]
I think they may be separate problems.  I did (1) above with the ORM turned on and off, with the regex fix in place, and there was no change in outcome.  The regex thing does make `t_process` pass if the ORM is off, though.
