### ISSUE TITLE
PRISM pptsum needs NoData set

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#307]
When the pptsum tif is computed for the system tests, the tif looks like a mask of the border of the united states.  Link to a png I exported from qgis:

https://drive.google.com/file/d/0B54rUezkgWNPRXhUZDFycEFTVEU/view?usp=sharing

**Comment by bhbraswell** [comment]
This could be totally fine depending on how the colors are mapped. Are all the white pixels the same value? I suspect black is a missing value (large negative) making all the valid values appear white.

**Comment by ags-tolson** [comment]
Clicking around on various pixels shows the values vary significantly; I'm going to assume this is qgis being stupid.

**Comment by ircwaves** [comment]
NoData value not set on product.
