### ISSUE TITLE
Sentinel-2 cloudmasking

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#311]
Since we are not using sen2cor, we need to wire in a cloud mask from another source.

Options:
+ update our FMask implementation to mesh with [Woodcock+Zhu](http://dx.doi.org/10.1016/j.rse.2014.12.014)
+ use [USGS-EROS CFMask](https://github.com/USGS-EROS/espa-cloud-masking/tree/master/cfmask) (which is declared unmaintained as of 2017-05-15)
+ use `python-fmask` implementation of FMask

**Comment by ircwaves** [comment]
The vector cloud mask that Sentinel includes is much less robust than FMask:
https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-1c/cloud-masks
![t19tch_20170612_msk-clouds-b00](https://user-images.githubusercontent.com/9936909/27552582-ef5affa2-5a75-11e7-9a8a-82d9ca909220.png)
![t19tch_20170612_pyfmask-and-msk-clouds-b00](https://user-images.githubusercontent.com/9936909/27552588-f63dd7a4-5a75-11e7-88c5-032b34bb339a.png)

**Comment by bhbraswell** [comment]
On the plus side, fmask looks pretty good. But, partially snowy scenes are the real test.

**Comment by ircwaves** [comment]
Same comparison: 2017-030 (cyan is snow)
![t19tch_20170130_msk-clouds-b00](https://user-images.githubusercontent.com/9936909/27557961-8fb030f4-5a89-11e7-81a6-6a51166d54f5.png)
![t19tch_20170130_pyfmask-and-msk-clouds-b00](https://user-images.githubusercontent.com/9936909/27557960-8fafce0c-5a89-11e7-9c87-357b4680e192.png)
![t19tch_20170130_msk-clouds-b00-zoom](https://user-images.githubusercontent.com/9936909/27557963-8fb420ba-5a89-11e7-93ac-89ab5a96a3a6.png)
![t19tch_20170130_pyfmask-and-msk-clouds-b00-zoom](https://user-images.githubusercontent.com/9936909/27557962-8fb3d39e-5a89-11e7-8838-82d2a0f5c222.png)

**Comment by ircwaves** [comment]
`python-fmask` does expose options for tweaking snow thresholds.  For some applications, masking out snow might be advantagous:
```
  --nirsnowthreshold NIRSNOWTHRESHOLD
                        Threshold for NIR reflectance (range [0-1]) for snow
                        detection (default=0.11). Increase this to reduce snow
                        commission errors
  --greensnowthreshold GREENSNOWTHRESHOLD
                        Threshold for Green reflectance (range [0-1]) for snow
                        detection (default=0.1). Increase this to reduce snow
                        commission errors
```

**Comment by bhbraswell** [comment]
Not great - snow is tough. Luckily mostly not a problem for our applications.

**Comment by ircwaves** [comment]
Right.  Looks like (based on the runway and highways) cold/icy pavement is highly likely to be confused for a cloud.

**Comment by ircwaves** [comment]
For our initial implementation, let's proceed with [python-fmask](https://bitbucket.org/chchrsc/python-fmask).  This library depends on their [rios](https://bitbucket.org/chchrsc/rios) library, which is just a raster handling library.
