### ISSUE TITLE
gdal version info

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#320]
1. current system test checksum dependent, and hence fail when using a different version of GDAL than what was used in creating the anointed checksums.  (future sys tests will be agnostic)
2. in general, GIPS should move toward GDAL2.
3. when CI server is redeployed, and system tests are overhauled, jobs should be scheduled to check GDAL1 and GDAL2 compatibility.

    | Driver | GDAL Version Used for test hash creation |
    | -------- | ------------------------------------------------ |
    | prism | 2 |
    | landsat | 1 |
    | sentinel2 | 1 | 
    | merra | 1 |
    | modis | 1 |

4. Note that GDAL version 1.11 is the current Ubuntu16.04 default.  And version 2.1 is the current version in UbuntuGIS xenial PPA.

**Comment by ircwaves** [comment]
Please update the table above with any other drivers you work on the system tests for.  I stopped there because they are probably all GDAL1 other than prism.

**Comment by ags-tolson** [comment]
This might be a good place to put GDAL 2 install instructions:

0. Strongly consider using a container (set OS to xenial/16.04, or use the DH installer script)
1. `apt-get install gdal-bin libgdal-dev`
2. Configure system to use ubuntu-gis ppa; stable/testing/unstable TBD:  https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa
3. `apt-get dist-upgrade`

**Comment by ircwaves** [comment]
Just cleaning up some things, and the fundamental issue here is settled -- we're headed to generally use GDAL2.

But I would recommend adding the ubuntugis ppa first, and then installing GDAL etc.  The above seems to create some extra traffic of installing to immediately uninstall and replace.
