### ISSUE TITLE
gips_project "directory does not exist!"

### ISSUE THREAD

**Issue by mcorbiere** [Applied-GeoSolutions/gips#33]
If you get this message, it is probably because the image you requested to project doesn't exist. I solved this by adding --fetch to the command. I'm noting this in the issue tracker because I've seen it multiple times and am always thrown off at first because the directory not existing shouldn't be a real problem (at least where it points to in the last line). I think an update to the exception in this case would be nice.

mcorbier@nile:/scratch/mcorbiere/unhserver$ gips_project modis -s cyanomap:osm_lakes -w "id='381870'" -d 2014-001 -p temp8td --res 1000 1000 -v4
GIPS Data Project (v0.8.2)
Retrieving inventory for site osm_lakes-381870
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gips/scripts/project.py", line 80, in main
    inv = ProjectInventory(datadir)
  File "/usr/local/lib/python2.7/dist-packages/gips/inventory.py", line 125, in __init__
    raise Exception('Directory %s does not exist!' % self.projdir)
Exception: Directory /scratch/mcorbiere/unhserver/osm_lakes_1000.0x1000.0_modis/381870 does not exist!

Data Project error: Directory /scratch/mcorbiere/unhserver/osm_lakes_1000.0x1000.0_modis/381870 does not exist!

**Comment by ircwaves** [comment]
So, if you `rm` the image that you `--fetch`ed, does that error return?

In the end, this is probably a sub-issue of issue #8.

**Comment by justinfisk** [comment]
I am seeing this error on NAS/NEX, but there is nothing to fetch. (I would like it to skip the lakes where there is no available scene.)
 ```
Retrieving inventory for site qgis_nhd4px_ls30_16_ls90_1_B-31bff93a-e06a-48d5-8424-f6667d6d63d0
Traceback (most recent call last):
  File "/home1/jfisk/venv/lib/python2.7/site-packages/gips/scripts/project.py", line 80, in main
    inv = ProjectInventory(datadir)
  File "/home1/jfisk/venv/lib/python2.7/site-packages/gips/inventory.py", line 125, in __init__
    raise Exception('Directory %s does not exist!' % self.projdir)
Exception: Directory /nobackup/jfisk/projects/31bff93a-e06a-48d5-8424-f6667d6d63d0 does not exist!

Data Project error: Directory /nobackup/jfisk/projects/31bff93a-e06a-48d5-8424-f6667d6d63d0 does not exist!
```
Curiously,  creating the directory allows it to move on despite nothing being written there.

**Comment by ircwaves** [comment]
So, the trouble is that lines 77 through 81 of [this block](https://github.com/Applied-GeoSolutions/gips/blob/master/gips/scripts/project.py#L71-L81) should be indented to match line 72.  

I have posted this in this manner, as I believe you are working in a separate repo, so it would not help you (@justinfisk) that I just committed the change to my branch.

**Comment by ircwaves** [comment]
Awesome to have fixed this bug so long ago....and not have released an update to our production environment.  Bit me again.  We're overdue for updating to a latest release.
