### ISSUE TITLE
aod & therefore atmo correction doesn't work on datahandler branch

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#335]
It looks like a lack of query/fetch bifurcation.  It tries to call query_provider while running MOD08 fetch, which raises an exception by default.  I took a minute to verify it worked as usual on the dev branch.

**Comment by ags-tolson** [comment]
PS - my test run was to use the command-line once in a DH-derived branch and once in dev:

```
gips_process sentinel2 -p ref -s /path/to/gips/gips/test/durham.shp -d 2017-01-10 -v6
```

**Comment by ircwaves** [comment]
It is the lack of the query_service method.

**Comment by ags-tolson** [comment]
#338 merge == this be fixed
