### ISSUE TITLE
CHIRPS driver

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#342]
CHIRPS is a gridded precipitation data set for Africa. It is 0.05 degree resolution, geographic projection (EPSG:4326), daily data set with a single measurement (rainfall) for years from 1981 to present. Latency appears to be about 3 weeks.

The data are fetchable as:
ftp://ftp.chg.ucsb.edu/pub/org/chg/products/CHIRPS-2.0/africa_daily/tifs/p05/{year}/chirps-v2.0.{year}.{month}.{day}.tif.gz

example:
ftp://ftp.chg.ucsb.edu/pub/org/chg/products/CHIRPS-2.0/africa_daily/tifs/p05/2004/chirps-v2.0.2004.01.01.tif.gz

This driver should be one of the more simple one both in terms of retrieving and processing. At this point we only need one product which is the exact value of the data in the asset.

See also:
/net/cluster/scratch/rbraswell/chirps/chirps-v2.0.2000.01.07.tif
```
braswell@blue:~/data/chirps$ gdalinfo chirps-v2.0.2000.01.07.tif
Driver: GTiff/GeoTIFF
Files: chirps-v2.0.2000.01.07.tif
       chirps-v2.0.2000.01.07.tif.aux.xml
Size is 1500, 1600
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-20.000000000000000,40.000000000000000)
Pixel Size = (0.050000000745058,-0.050000000745058)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2015:09:02 17:09:49
  TIFFTAG_DOCUMENTNAME=/home/sandbox/chirps/v2.0/daily_downscaled_by_monthly/africa_full_rescale_again/01mm/2000/chirps-v2.0.2000.01.07.tif
  TIFFTAG_IMAGEDESCRIPTION=IDL TIFF file
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=IDL 8.5, Exelis Visual Information Solutions, Inc., a subsidiary of Harris Corporation.
  TIFFTAG_XRESOLUTION=100
  TIFFTAG_YRESOLUTION=100
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -20.0000000,  40.0000000) ( 20d 0' 0.00"W, 40d 0' 0.00"N)
Lower Left  ( -20.0000000, -40.0000012) ( 20d 0' 0.00"W, 40d 0' 0.00"S)
Upper Right (  55.0000011,  40.0000000) ( 55d 0' 0.00"E, 40d 0' 0.00"N)
Lower Right (  55.0000011, -40.0000012) ( 55d 0' 0.00"E, 40d 0' 0.00"S)
Center      (  17.5000006,  -0.0000006) ( 17d30' 0.00"E,  0d 0' 0.00"S)
Band 1 Block=1500x1 Type=Float32, ColorInterp=Gray
  Min=-9999.000 Max=65.942 
  Minimum=-9999.000, Maximum=65.942, Mean=-4871.789, StdDev=4998.761
  Metadata:
    STATISTICS_MAXIMUM=65.94189453125
    STATISTICS_MEAN=-4871.7888879602
    STATISTICS_MINIMUM=-9999
    STATISTICS_STDDEV=4998.7607061701
```

**Comment by bhbraswell** [comment]
@bhbraswell document product units and create tile shapefile

**Comment by ags-tolson** [comment]
Couple questions:
* Each product seems to be approx 9M, so the entire corpus of africa precip products (1981-present) is approx 9 x 365 x 35 = 112G.  So space can be saved by symlinking + vsi paths but it's not clear we care; should I do this instead of extract the product files?
* Once that decision is made, should I take the time to put in additional metadata like we usually do, no-data value (-9999), gips version, etc?  I don't think there's a way to do that if the products are symlinks, right?

**Comment by bhbraswell** [comment]
Symlinking makes sense to me because otherwise the products would be exactly equal to the assets, but I don't feel strongly about it.

Since the assets are tiffs with missing value specified, then I would think you could access that metadata with the symlinked product

**Comment by ags-tolson** [comment]
Okay, I'll symlink, which answers the metadata question

**Comment by ags-tolson** [comment]
So it doesn't get lost:  My local branch `342-chirps-tests` contains unit tests and the beginning of an integration test; I intend to PR at some point.

**Comment by bhbraswell** [comment]
There is a request from the science team for this driver to be usable by 8/4.

**Comment by ags-tolson** [comment]
tests in PR #348
