### ISSUE TITLE
DH - add end-to-end support for more PPJs, and add 'export' as the first new one

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#350]
DH is hardcoded to support only one workflow.  It needs to support more:
* new PPJ:  Export (ie query, fetch, process, export, without aggregate)
* Retain existing PPJ export-and-aggregate
* Jobwise-configurable choice of where to save output, or else use current behavior (immediate cleanup)

**Comment by ra-tolson** [comment]
This question is being answered elsewhere.
