### ISSUE TITLE
Add new vegetation indice to Landsat driver

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/gips#361]
Could we please add 'VARI' (Visible Atmospherically Resistant Index) to the Landsat driver?  @ircwaves noticed that it is already implemented in gippy.  Let me know if I need to provide more information.

**Comment by ircwaves** [comment]
Got a link to that publication you were looking at that described the index?

**Comment by lledoux** [comment]
Sure! 
[vari.pdf](https://github.com/Applied-GeoSolutions/gips/files/1211586/vari.pdf)

**Comment by ircwaves** [comment]
thanks!

**Comment by ags-tolson** [comment]
Wow cool github supports PDF attachments to issues; I had no idea.

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by ircwaves** [comment]
@lledoux -- go into your gips repo and `git pull` -- and you should be set to go on `vari`.
