### ISSUE TITLE
landsat datahandler compatibility

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#362]
![2017-08-09-131421_837x149_scrot](https://user-images.githubusercontent.com/9936909/29134466-b23703ee-7d04-11e7-9c9f-887bc2a351fd.png)

Shown above, the data handler catalog requires that 
   `gips.data.landsat.landsatData._products[p]['bands']`
be updated to be a list of metadata dicts.  Not sure how I missed this in the DH-compat task.

**Comment by ags-tolson** [comment]
CF #257 I think?

**Comment by ircwaves** [comment]
that's true @ags-tolson.   I think this will need to be fixed for you to test the DH masking workflow, so you may need to do this before testing #357 .
