### ISSUE TITLE
update GIPSParsers for grid exports

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#387]
Looks like the key here is to make sure that whatever `-s` option accepts is digestable by `SpatialExtent.factory`.

**Comment by justinfisk** [comment]
added a -r/--rastermask option to inventory parser which is mutually exclusive with site

It is still possible that someone could call SpatialExtent.factory with both, so for now, it preferentially uses rastermask if supplied and ignores site related kwargs (key, where)

commits in 2add7d9
