### ISSUE TITLE
alter gips.tiles.Tiles.mosaic to handle raster derived SpatialExtent

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#389]
In the case of rasters, perhaps we would want to make a `utils.gridded_export` that takes the `site_mask` and a list of `rasters`, and warps them into an all-no-data file (created from the site mask), and then masks the image. 

`man gdalwarp` skrev:
>      Mosaicing into an existing output file is supported if the output file
>      already exists. The spatial extent of the existing file will not be
>      modified to accommodate new data, so you may have to remove it in that
>      case, or use the -overwrite option.

**Comment by justinfisk** [comment]
created utils.gridded_mosaic and hooked up to Tiles.mosaic using the above plan.

Probably needs a way to specify sampling method and possibly other options to gdalwarp

committed in 2add7d9
