### ISSUE TITLE
MODIS tile boundary nonsense

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#39]
I found that the tile definition shape file we were using was not perfectly square, or rectangular, in the sinusoidal coordinate system. I searched for an official tile vector file and could not found one. So I made one using the the data bounds. I copied it to /titan/data/modis/vectors/. It has 317 features and they look OK.

![tiles](https://cloud.githubusercontent.com/assets/3209308/14961847/e4c84524-1069-11e6-8852-f3bcde13ae43.png)

I will push these tiles into the repo unless someone has an objection..

**Comment by ircwaves** [comment]
That sounds reasonable.  For the data bounds, did you just pull the bounding boxes of images?

**Comment by ircwaves** [comment]
Hey, @bhbraswell , when you say that you made that using the data bounds, do you mean that you used the values from Goddard?

http://modis-land.gsfc.nasa.gov/pdf/sn_bound_10deg.txt

**Comment by bhbraswell** [comment]
No, because those are just four points in lon/lat space. 

I used the bounds of actual image tiles. See https://github.com/Applied-GeoSolutions/gips/blob/master/gips/data/modis/make_tiles.py

See

**Comment by ircwaves** [comment]
Ah...I see now...thanks.

**Comment by ircwaves** [comment]
by dc078a0
