### ISSUE TITLE
inspect and rectify acolite metadata

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#390]
https://github.com/Applied-GeoSolutions/gips/blob/f21a46120038514cee9bd87c6cdcad3d5b77e176/gips/data/landsat/landsat.py#L779-L784

In the above, either `imeta` can be dropped or second assignment can be make and `update`.

**Comment by ags-tolson** [comment]
Looks like imeta is needed after all:

```
(Pdb) imeta
{'GIPS-landsat Version': '1.0.0', 'GIPS Version': '0.8.2'}
```

**Comment by ircwaves** [comment]
Cool...so just wrap that assigned dict in a `.update( ... )`?

**Comment by ags-tolson** [comment]
Yes, that's working in my branch.
