### ISSUE TITLE
test drive new ACOLITE

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#391]
install new version of ACOLITE on dev box, and check if tests pass.

**Comment by ircwaves** [comment]
if #391 presents any issues
check if NT has an updated ACOLITE config file.

**Comment by ircwaves** [comment]
http://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=3&t=67

**Comment by ags-tolson** [comment]
It looks like acolite doesn't work on Ubuntu 16.04 without fiddling.  I get "error while loading shared libraries: libXp.so.6: cannot open shared object file: No such file or directory".  Digging I find that libxp6 isn't available on ubuntu 16.04, which means IDL 8.4 won't run.  Harris claims that IDL 8.6 doesn't have this issue, [see comment by somebody named Starbuck](http://www.harrisgeospatial.com/Support/SelfHelpTools/HelpArticles/HelpArticles-Detail/TabId/2718/ArtMID/10220/ArticleID/16146/IDL-fails-to-install-on-Linux-What-to-do.aspx).

**Comment by ircwaves** [comment]
This is probably what I did [(src)](http://www.harrisgeospatial.com/Support/SelfHelpTools/HelpArticles/HelpArticles-Detail/TabId/2718/ArtMID/10220/ArticleID/16146/IDL-fails-to-install-on-Linux-What-to-do.aspx):
> On some recent Ubuntu versions (such as version 15.10) the libXP package needs to be downloaded from the web first. The best place to look for these downloads is the Debian website and  here is a link to download libxp6 from there https://packages.debian.org/stable/libs/libxp6.

But that URL is getting more stale...it is now https://packages.debian.org/oldstable/libxp6 emphasis on the **old**.

Plus a `dpkg -i Downloads/libxp6_1.0.2-2_amd64.deb`  and a `apt-get -f install`.  Not long-term viable, but works for now.

**Comment by ags-tolson** [comment]
Started to use a new asset file with fewer clouds.  The before-and-after looks like it passes and the products in qgis look good, so we're all set I think.  There's no deliverable for this but some checksums in expected/ so I'm callin' it good.
