### ISSUE TITLE
add ACOLITE products to Sentinel2 driver.

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#392]

**Comment by ags-tolson** [comment]
how 2 add driver 2 sentinel 2 if doesn't need atmo correction:

* [ ] add the product to the _products dict
*  [ ] make a $prod_geoimage() method to generate the GeoImage; follow pattern of others.
* [ ] add a stanza to the conditional below where $prod_geoimage is called.
*  [ ] add the product to the dependency dict above.
* [ ] update system tests

**Comment by ags-tolson** [comment]
PR #397 fixes this.
