### ISSUE TITLE
usgs module search doesn't work with cloud cover parameter

### ISSUE THREAD

**Issue by naterubin** [Applied-GeoSolutions/gips#400]
The `usgs` module, which is now used for querying landsat tiles, consistently returns 0 results if the cloud cover parameter is specified, regardless of the value. This currently renders the `pclouds` argument of landsat's `filter` method useless.

**Comment by ircwaves** [comment]
Looks like we DIY by fetching the metadataUrl.  Also, we should probably emit a warning if the API version changes from what we're writing this to match.
```
{u'access_level': u'approved',
 u'api_version': u'1.3.0',
 u'data': {u'firstRecord': 1,
           u'lastRecord': 1,
           u'nextRecord': 1,
           u'numberReturned': 1,
    [ snip ]
                         u'metadataUrl': u'https://earthexplorer.usgs.gov/metadata/xml/12864/LC80120302017213LGN00/'
 [ snip ]
```

**Comment by ircwaves** [comment]
We need this to stop downloading cloudy scenes, especially for any co-registration, where we want to get the nearest cloud-free scene for registration.

**Comment by naterubin** [comment]
TODO: Wire this into the `filter` method.
