### ISSUE TITLE
gips_project cdl errors

### ISSUE THREAD

**Issue by bziniti** [Applied-GeoSolutions/gips#414]
This is low priority and maybe just a user error. 

```
bziniti@mekong:~$ gips_project cdl -s /net/cluster/scratch/bziniti/sarag_us/shapes/sarag_us_regions.shp --outdir /net/cluster/projects/NASsarag1/data/US_GroundTruth --res 30 30
GIPS Data Project (v0.9.1-dev)
Fatal: 1 error(s) occurred:
Error: could not connect to server: Connection timed out
    Is the server running on host "oka.ags.io" (10.0.0.4) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection timed out
    Is the server running on host "oka.ags.io" (2603:3005:1503:7ce0::8d4e) and accepting
    TCP/IP connections on port 5432?
```

```
bziniti@schedprd:~$ qsub -I -q NASsarag0_ -lnodes=rio -v PATH=$PATH:/usr/local/bin
qsub: waiting for job 28728.schedprd.ags.io to start
qsub: job 28728.schedprd.ags.io ready

bziniti@rio:~$ gips_project cdl -s /net/cluster/scratch/bziniti/sarag_us/shapes/sarag_us_regions.shp --outdir /net/cluster/projects/NASsarag1/data/US_GroundTruth --res 30 30
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/usr/local/bin/gips_project", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gips/scripts/project.py", line 41, in main
    args = parser0.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 42, in parse_args
    self.add_data_sources()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 161, in add_data_sources
    for src, desc in data_sources().items():
  File "/usr/local/lib/python2.7/dist-packages/gips/utils.py", line 218, in data_sources
    raise Exception('ERROR: archive %s is not a directory or is not available' % key)
Exception: ERROR: archive modis is not a directory or is not available
bziniti@rio:~$ gips_info cdl
GIPS Data Repository error: ERROR: archive modis is not a directory or is not available
```

**Comment by ags-tolson** [comment]
I think this is legit, because you can't tell from the error message what went wrong.  At the very least it should tell you the path to the repository in addition to the driver name.

**Comment by ags-tolson** [comment]
And for the network error it's the same thing:  What is it trying to _do_?  I happen to know 5432 is the port for postgres which means your ORM is probably turned on, while oka has been turned off, so you probably need to change your database settings.

**Comment by bziniti** [comment]
How do I change my database settings or know if that is the problem? Basically, I'm trying the same command but first tried on Mekong and then on Rio and I get two different errors.

**Comment by bhbraswell** [comment]
I think Beth is using system-installed GIPS on the cluster, so she is not responsible for db settings in this case. Is that right?

**Comment by bziniti** [comment]
I believe at least I'm trying to use the system-installed GIPS on the cluster.

**Comment by bziniti** [comment]
Also not sure this matters, but I didn't include the date range in my commend. Should be -d 2016-01-01 2016-12-31. When I included this it didn't give an error, but also didn't do anything. After some more checking, these dates (this year 2016) does not exist in /titan/data/CDL/tiles/ for all but on of the regions I'm looking. Do I need to get this data first?

**Comment by ircwaves** [comment]
I've fixed the db settings on `mekong` and the `modis` settings on rio.   @bziniti please type 
```
export GIPS_ORM=false
```
before you try again.

**Comment by ircwaves** [comment]
Along the lines of [the rule of silence](http://www.linfo.org/rule_of_silence.html), I believe this was addressed.  If not so, @bziniti , please re-open.
