### ISSUE TITLE
landsat coreg product

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#429]
Add a product option to coregister landsat onto Sentinel-2

**Comment by ircwaves** [comment]
Earlier estimate of timing was off.  Current ballpark for coregistration is over an hour.  
Need to determine where/why it is taking so long.  I suggest adding `verbose_out`s that include a time delta from the start of the process function.

[branch](../tree/landsat-coreg-product/)

**Comment by ircwaves** [comment]
Probably better to use `sentinel2Data.inventory(...)` here, because this fetches the file but doesn't update the database inventory:
https://github.com/Applied-GeoSolutions/gips/blob/5f0dcf9d69ac16591a0ba95049dedeedd38b722f/gips/data/landsat/landsat.py#L1406-L1411

**Comment by naterubin** [comment]
12 minutes of converting jp2 to tif:

* replace with VRT

1 hour 10 minutes for CookieCutter:

* need to look into this

**Comment by ircwaves** [comment]
(side note: we need to replace lots of stuff in the sentinel2 driver with VRTs)

**Comment by ircwaves** [comment]
For the CookieCutter, set `crop=True` in the call.  That should make the resulting file significantly smaller.

**Comment by naterubin** [comment]
Instead of using CookieCutter at all, all relevant are `gdal_merge`d together, which only takes a few minutes, reducing the processing of a coreg product to about 4 minutes.

**Comment by ircwaves** [comment]
And in the event that you've coregistered a product for a given tile+date previously, additional products require very minimal (seconds) of additional processing time.
