### ISSUE TITLE
Fully automate gips deployment

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#43]
Seems like gips is a good candidate for full automation and Rob is already putting it in containers; see comments here for extra steps:

https://github.com/Applied-GeoSolutions/gips/pull/42

In addition, if `install.sh` is used for this, it should be parameterized so the user can say "clone the repo to directory D please" or "don't clone at all, use directory D as the repo."  Other options suggest themselves, such as performing gips config steps and choosing a root path for the data repo.  There's also a difference between deploying to production and deploying for dev, so that could be accounted for somehow.

**Comment by ircwaves** [comment]
This plus unit tests would put us in good shape to set up continuous integration.

**Comment by ircwaves** [comment]
[the branch](/Applied-GeoSolutions/gips/tree/bs-deploy)

**Comment by ircwaves** [comment]
has merged into [datahandler](Applied-GeoSolutions/gips/tree/datahandler)
