### ISSUE TITLE
S2 EVI & SATVI have too many no-data values

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/gips#433]
Oh jeeze, I feel like I should have caught this sooner, but- it seems like the EVI Sentinel-2 products have a lot of no data values (-32768) where there shouldn't be any (no data values here are white):

![s2_evi_nodata](https://user-images.githubusercontent.com/16612231/32008062-4615e8cc-b979-11e7-9309-5a210bdea41d.png)

This is the corresponding NDVI image:
![s2_ndvi_same_areaasevi](https://user-images.githubusercontent.com/16612231/32008087-572350aa-b979-11e7-8893-bb4016f6bd19.png)

**Comment by lledoux** [comment]
Also- Sentinel-2 SATVI images are all NAN's (-32768):
![satvi_nans](https://user-images.githubusercontent.com/16612231/32014275-9e379156-b98b-11e7-8748-b404b1e73ef8.png)

**Comment by ags-tolson** [comment]
@lledoux can you point me at the problematic scene you found?  tile & date would be ideal.

**Comment by ircwaves** [comment]
@ags-tolson let's get together after standup and discuss what you've found so far.  I've verified this issue using `19TCH` and `2017-283`.

**Comment by lledoux** [comment]
Sorry for the delay! This particular tile data is in ```/titan/data/sentinel2/tiles/48PUS/2017031/ ```

**Comment by ags-tolson** [comment]
those are great details, thanks to you both.

**Comment by ircwaves** [comment]
Re-capping our conversation yesterday, It looks like setting the `gain` on both the input and the output geoimages should address this.  When you've implemented and run this, it should be discernible from the `gdalinfo -stats ${TIF}` output whether the gain is having the desired effect (*N.B.: `gdalinfo` does not use gains nor offsets when computing image statistics*).

**Comment by ags-tolson** [comment]
Tentatively there's been success with `SetGain(0.0001)` for indices products.  Remaining tasks are:

- [ ] install SIXS et al on my container to set up for atmo correction
- [ ] run `rad` and `ref` and confirm they look good post-`SetGain`

**Comment by ags-tolson** [comment]
Wellp, turns out all four of the central products in the driver needed revision.  Tentative fix is in branch  `433-draft-main-prod-fixes`.  Once I started adding gains to things it started breaking "downstream" products; next is testing that the indices get reasonable results.

I call them 'draft fixes' because I'm not confident my math is right; I'd really like someone knowledgeable to verify the resulting products.

**Comment by ags-tolson** [comment]
Place to look for products resulting from that branch:

`/scratch/tolson/pub/433-trial-central-prods/`

There's some asset jp2s in there too for comparison.

**Comment by ircwaves** [comment]
Which branch generated these?

**Comment by ags-tolson** [comment]
It's the one I mentioned above, `433-draft-main-prod-fixes`.

**Comment by ircwaves** [comment]
Sorry.  I wish GH had a way to auto ref branches.  I stick them in as links for lack of a better way. [../compare/dev...433-draft-main-prod-fixes](../compare/dev...433-draft-main-prod-fixes)

**Comment by lledoux** [comment]
So in order to be able to process correct EVI and SATVI, do I need to have that particular gips branch?  I just tried processing both products (on rio, in my virtual environment that is 'up-to-date' with master) yesterday, and I'm still having the same problem...

EVI (for tile 48PTT, 2015365):
![evi](https://user-images.githubusercontent.com/16612231/33373898-e8f0d3c2-d4d1-11e7-9347-04473b525ba4.png)

* The screenshot of the SATVI for the same tile and date would not be helpful to show, as it is all NaNs.

**Comment by ircwaves** [comment]
@lledoux @bhbraswell -- I think you may need to re-process the `'ref'` product in that directory (use `--overwrite` should update it).  If that fixes it, then there is a lurking bug in the guts of the sentinel2 driver.

```
icooke@north:/titan/data/sentinel2/tiles/48PTT/2015365$ ls -l *ref.tif
-rw-rw-r-- 1 10087 staff 361726198 Oct 25 15:00 48PTT_2015365_S2A_ref.tif
```

**Comment by lledoux** [comment]
It turns out that the reflectance images that had already been processed before the EVI and SATVI fix were mucking up some things.  Once the ref images are re-processed, the EVI and SATVI look correct.
