### ISSUE TITLE
handle new asset collections (e.g. MODIS collection 6)

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#44]
MODIS collection 6 reprocessing of MCD43 is almost done. For some things, using the current (C5) data is fine. For others, e.g. looking for possibly small trends over time, it has to be C6.

Since we have so much MODIS I think it makes sense for those data to co-exist. As an interim measure I can implement metadata that records the data version on the products I'm using and make an option that will force overwriting 5 with 6.

**Comment by ircwaves** [comment]
I have put some remedial asset versioning into `gips.data.core`, `gips.data.landsat`, and `gips.data.prism`.  At the moment, this is only checked at `archive` time.  It should be pretty straight forward to expand to have fetch use this versioning.

**Comment by bhbraswell** [comment]
Since we're still sketching this out, I think the data (asset) version switch might need to be smarter than I suggested. For example I am going to want to do two identical analyses, one with the old version and one with the new version. But for many use cases, the user will want to ignore the version and just use whatever we have, with preference for the newer version.

**Comment by matthewhanson** [comment]
@ircwaves @bhbraswell An alternative approach that could be done without a ton of effort is to simply copy the MODIS driver, call it MODISv6, and treat it as another sensor.   That way it doesn't have to be smart about versioning multiple files (which could be a mess), and would work very well from an analysis standpoint, because it would be the same as comparing data across multiple sensors.

**Comment by bhbraswell** [comment]
I usually like that sort of solution but I wonder if we might have to take the messier route. In my modis example, you might have a case where someone only wants collection-6, or you might have a case where someone either doesn't care or 

On the other hand, maybe just making the behavior of --sensors in the request more flexible could solve the problem.

**Comment by ags-tolson** [comment]
Some work for this issue is in branch named `modis-6`.

**Comment by bhbraswell** [comment]
There are actually two issues that might need to be separated. One is that asset releases can be versioned (e.g. modis collections 5 and 6). Another is that individual assets can be versioned, which coincidentally happened with some collection 6 files. I asked the MCD43 PI Crystal Schaaf about this and she said that it's early in the release and they found an issue in some of the files. This could in principle happen with any of the data sets.

Example:
```
MCD43A4.A2007362.h12v03.006.2016103202923.hdf
MCD43A4.A2007362.h12v03.006.2016125193728.hdf
```

We need plan for both of these things.

**Comment by bhbraswell** [comment]
@ircwaves points out that there is a mechanism to handle asset file versions (Asset.updated).

There also is a way to force an update (Asset.archive with update=True), and it is only implemented in the gips_archive script, but could be used anywhere.

**Comment by ircwaves** [comment]
Yessssssaaahhh!!!  You are correct, SIR!  HIYO!!!!!

Per my dog-walk-email yesterday, I like the idea of integrating that asset versioning update into the fetch.  Also, I realized that I have implemented the 2-layered asset versioning scheme in the prism driver.

*IFF* the band name differences could be handled, then the trick would be to have tha asset version be 
```
float('{}.{}'.format(COLLECTION_ID, COLLECTION_VERSION))
```
where `COLLECTION_ID in [5, 6]` and COLLECTION_VERSION is the versioning that Crystal Schaaf mentioned.  That would lead to `gips.data.core.Data.updated` handling the versions with a simple `>`.

**Comment by bhbraswell** [comment]
The band indexing differences could be handled by doing it slightly differently depending on the value of collection (5 or 6). 

So in this scheme, MODIS 6 file compared to a MODIS 5 files would just be considered an update.

OK, that's fine I think, because that's basically what it is. We just will want to expose the "update" asset option for gips_process and gips_project.

**Comment by ircwaves** [comment]
Yeah, it should be moved from `gips.scripts.archive` into `gips.parsers.add_inventory_parser`.  

But, the combination `--fetch --update` would result in querying to see if newer versions of all existing assets were available, right?  Don't know how much that will slow things down.  Some sort of *don't query iff version is >= X* might alleviate that.

**Comment by bhbraswell** [comment]
Having said/ done all this: I'm struggling to think of a case where there would ever be a clash between versions, since files are automatically downloaded, and no files downloads would be attempted if the requested asset exists (i.e. the pattern matches) but the asset pattern currently will match any version.

So, adding a feature to force update is a good thing to work toward, but I don't understand why the naive MODIS 6 changes caused anything to break, except that the reflectance bands are stored differently.

**Comment by bhbraswell** [comment]
First I think I have to modify core Data.fetch so that it ignores existing assets. Right around here:

```
                    # if we don't have it already                                                                                                                                    
                    if not cls.Asset.discover(t, d, a):
                        try:
	                    cls.Asset.fetch(a, t, d)
                            fetched.append((a, t, d))
                        except Exception, e:
                            VerboseOut(traceback.format_exc(), 4)
                            VerboseOut('Problem fetching asset: %s' % e, 3)
```

**Comment by bhbraswell** [comment]
I believe the current changes in modis-6 take care of this issue. Basically there is now a "--update" option that, in addition to it's behavior in the archive script (moving staged files into the archive if they are newer), it will force a fetch when --fetch is specified even if there is a matching asset in the archive. 

I tested by deleting and renaming files in my local data archive, so there are 'tests' but not tests. @ircwaves and @ags-tolson please advise.

**Comment by ircwaves** [comment]
@bhbraswell -- with the modis6 branch merged, I believe this is handled, but as you are the originator, I'd prefer that you confirm or deny this, and close or fight on, respectively.

**Comment by ags-tolson** [comment]
(Merged) PR for convenience:  https://github.com/Applied-GeoSolutions/gips/pull/68

Normally I make a note of that in the issue, forgot this time, sorry!  :bow:

**Comment by ags-tolson** [comment]
This sat unresolved for two months after the branch merged; let's assume the fix was satisfactory and move on.
