### ISSUE TITLE
ASTER driver

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#446]
begin to implement ASTER driver w/o fixed tile grid (untiled)

`Asset.__init__` and `Asset.get_geometry` are both likely to work well with the CMR.

* [earthdata wiki](https://wiki.earthdata.nasa.gov/display/CMR/pyCMR)

**Comment by bhbraswell** [comment]
Probably should close #101. also there is a branch called 101-aster

**Comment by ircwaves** [comment]
Nahhh... Let's call this a dupe and kill it.
