### ISSUE TITLE
migrate MODIS indices to separate products

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#453]
As the MODIS `indices` product is often used for only one or two of its sub-products (NDVI, LSWI, VARI, BRGT, SATVI, EVI, QC), they should probably be moved to separate products, with the `'indices'` product being deprecated.

**Comment by ags-tolson** [comment]
More tasks for this issue, which will build on #439:
- [ ] new product group, 'Indices', for everything from 'indices' and tillage stuff from #439 
- [ ] deprecation warning for indices product, but leave it in place
- [ ] delete 'refl' block completely
- [ ] remove notion of 'tillage indices' from source code; all indices are done similarly in the same code block
