### ISSUE TITLE
acolite throws an error when it's directory is not writable

### ISSUE THREAD

**Issue by naterubin** [Applied-GeoSolutions/gips#473]
When the `ACOLITE_DIR` (in this case `/opt/acolite_linux`) is not writable by a user, the process reports this cryptic error message and exits:

```
'IDL Version 8.4 (linux x86_64 m64). (c) 2014, Exelis Visual Information Solutions, Inc.\n\n% ACOLITE: Running ACOLITE for 1 image.\nError -254:  Error opening file. Unit'
```

The solution, naturally, is to make sure that `ACOLITE_DIR` is writable. Although this issue is solved, it is worth recording the fix as it is hard to determine what is going on solely from the error message.

**Comment by ags-tolson** [comment]
It also explains why I didn't see the error:  I believe my `ACOLITE_DIR` was in my homedir during my testing, and therefore owned by me.
