### ISSUE TITLE
AOD "bad request"

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#490]
Is Monday the new Wednesday?

```
Traceback (most recent call last):
  File "/gips/gips/utils.py", line 578, in cli_error_handler
    yield
  File "/gips/gips/data/aod/aod.py", line 150, in query_provider
    resp.raise_for_status() # some errors don't raise otherwise
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD08_D3/2018/121.json
```
This cascades down into the eventual "Directory [] does not exist!" error message.

<img width="758" alt="untitled" src="https://user-images.githubusercontent.com/3209308/40308549-9969d994-5cd4-11e8-9ace-66c6dbfe5d96.png">

**Comment by bhbraswell** [comment]
Day 121 is too recent

**Comment by ircwaves** [comment]
If today is DOY 141, should `'aod'` latency be bumped up from `7` to `30`ish?

**Comment by ags-tolson** [comment]
@ircwaves is this where the asset type's latency value -- haha beat me to it : ]

**Comment by ags-tolson** [comment]
According to MODIS there's a new collection, 6.1, that we should switch to for anything past May:

1. Collection 61 link:
https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/61/MOD08_D3/
2. Collection 6 data prior to May 1 are still available:
https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD08_D3/

**Comment by ags-tolson** [comment]
New gitlab issue to handle this:  https://gitlab.com/appliedgeosolutions/gips/issues/541

**Comment by ircwaves** [comment]
[Broader announcement](https://modis-atmosphere.gsfc.nasa.gov/documentation/collection-61)

**Comment by ircwaves** [comment]
AOD has been bumped to Collection 6.1
