### ISSUE TITLE
Landsat7 ESUN

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#493]
I can't remember if there is some reason why GIPS uses different ESUN values (a) than USGS recommends (b)

(a) `'E': [2638.35, 2031.08, 1821.09, 2075.48, 1272.96, 246.94, 90.61, 369.36, 0, 0]`
(b) https://landsat.usgs.gov/esun

**Comment by ircwaves** [comment]
For Landsat 8, USGS doesn't provide the ESUN values.  The differences arise from differences in the Thulier solar spectrum (as recomended by the Committee on Earth Observation Satellites (CEOS)), versus the ChKur solar spectrum used by the folks at Spectral Sciences (MODTRAN).

**Comment by bhbraswell** [comment]
THANKS

**Comment by bhbraswell** [comment]
Does your statement apply also to L7? That was actually what I was wondering about. I'm just noting that the table on the USGS site for L7 has different numbers. Sorry if I'm missing something.
