### ISSUE TITLE
some gips functions on nile aren't working

### ISSUE THREAD

**Issue by dchowdhury** [Applied-GeoSolutions/gips#50]
```
dchowdhury@nile:/scratch/dchowdhury/RICEDST/VHI/ARMSMOLA_250.0x250.0_modis$ gips_inventory landsat -h
Traceback (most recent call last):
  File "/usr/local/bin/gips_inventory", line 9, in <module>
    load_entry_point('gips==0.8.2', 'console_scripts', 'gips_inventory')()
  File "/usr/local/lib/python2.7/dist-packages/gips/scripts/inventory.py", line 39, in main
    args = parser0.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 42, in parse_args
    self.add_data_sources()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 159, in add_data_sources
    for src, desc in data_sources().items():
  File "/usr/local/lib/python2.7/dist-packages/gips/utils.py", line 213, in data_sources
    raise Exception('ERROR: archive %s is not a directory or is not available' % key)
Exception: ERROR: archive modis is not a directory or is not available

dchowdhury@nile:/scratch/dchowdhury/RICEDST/VHI/ARMSMOLA_250.0x250.0_modis$ gips_info
GIPS Data Repository error: ERROR: archive modis is not a directory or is not available

dchowdhury@nile:/scratch/dchowdhury/RICEDST/VHI/ARMSMOLA_250.0x250.0_modis$ gips_process -h
Traceback (most recent call last):
  File "/usr/local/bin/gips_process", line 9, in <module>
    load_entry_point('gips==0.8.2', 'console_scripts', 'gips_process')()
  File "/usr/local/lib/python2.7/dist-packages/gips/scripts/process.py", line 38, in main
    args = parser0.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 42, in parse_args
    self.add_data_sources()
  File "/usr/local/lib/python2.7/dist-packages/gips/parsers.py", line 159, in add_data_sources
    for src, desc in data_sources().items():
  File "/usr/local/lib/python2.7/dist-packages/gips/utils.py", line 213, in data_sources
    raise Exception('ERROR: archive %s is not a directory or is not available' % key)
Exception: ERROR: archive modis is not a directory or is not available
```

**Comment by dchowdhury** [comment]
Related (?): modis seems unavailable in gips on Rio.

dchowdhury@rio:/scratch/dchowdhury/RICEDST/VHI$ gips_inventory modis -s ../Shapefiles/CA_new.shp
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/dchowdhury/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
error: argument command: invalid choice: 'modis' (choose from 'aod', 'weld', 'sarannual', 'cdl', 'landsat', 'prism', 'merra', 'daymet', 'sar')
usage: gips_inventory [-h]
                      {aod,weld,sarannual,cdl,landsat,prism,merra,daymet,sar}
                      ...

GIPS Data Inventory (v0.8.2)

positional arguments:
  {aod,weld,sarannual,cdl,landsat,prism,merra,daymet,sar}
    aod                 Aerosol Optical Depth from MODIS (MOD08)
    weld                WELD Landsat
    sarannual           Synthetic Aperture Radar PALSAR Mosaics
    cdl                 Crop Data Layer
    landsat             Landsat 5 (TM), 7 (ETM+), 8 (OLI)
    prism               PRISM Gridded Climate Data
    merra               Modern Era Retrospective-Analysis for Research and
                        Applications (weather and climate)
    daymet              Daymet weather data
    sar                 Synthetic Aperture Radar PALSAR and JERS-1

optional arguments:
  -h, --help            show this help message and exit

**Comment by ags-tolson** [comment]
Looks like this is related to known data outages rather than gips itself; closing.
