### ISSUE TITLE
Need workshop release

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#52]
Steve needs a specific GIPS version to include in instructions to participants in a training workshop. No new features are needed, he just needs to tell them what to check out and to be able to run through everything before he leaves and have it be the same when he gets there, so master might not work.

**Comment by ircwaves** [comment]
I believe that Steve is working with the latest master, so I gave him the appropriate git checkout line.  Nothing wrong.  He's just looking to make sure what's he's doing is repeatable in Ghana during the workshop, if master marches onward.

**Comment by bhbraswell** [comment]
I'll review with Steve, nothing further to do. Thanks --
