### ISSUE TITLE
(possible) bad output from `gips_process modis` and `gips_tiles modis`

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#54]
The output from `gips_process modis . . .` seems to have broken symlinks; the test for this is `t_process` in `gips/test/sys/t_modis.py`.

The output from `gips_tiles modis` seems to be the creation of an empty directory; test for this is `t_tiles` in `gips/test/sys/t_modis.py`.

Those tests are either in branch `46-sys-tests` or else `master` if it's merged; they're programmed to assume the given output passes for now, in case this is correct behavior.  See PR #55

**Comment by bhbraswell** [comment]
@ircwaves, is this or would this be associated with any previously noticed behavior with GIPS in the AGS data archive?

**Comment by bhbraswell** [comment]
Would it be possible to add a test that has just one product (e.g. using "-p indices") so that we can see if the problem is associated with having to plow through all the products, which is an unusual use case. Sorry if I'm reading the test wrong, but I think that's what it is doing.

**Comment by ags-tolson** [comment]
So I ran the test manually and observed that entering commands in my shell had the same effect as running it in the test suite.  Then I ran it both with and without `-p indices` as you suggested, and I'm afraid there were no changes.

**Comment by ags-tolson** [comment]
I ran the same manual command line on one of our servers and talking to the AGS central gips (I believe); here's the output:

```
$ gips_tiles modis -s nhseacoast/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4 --outdir testout --notld -p indices
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/tolson/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
GIPS Tiles (v0.8.2)
Retrieving inventory for site NHseacoast-0
2012-12-01 tile h12v04: 1 files warped
gdalwarp /data2/modis/tiles/h12v04/2012337/h12v04_2012337_MCD_indices.tif testout/h12v04/h12v04_2012337_MCD_indices.tif -t_srs "PROJCS["WGS_1984_UTM_Zone_16N",GEOGCS["GCS_WGS_1984",DATUM["WGS_1984",SPHEROID["WGS_84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-87],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]" -tr 926.625433138 926.625433139 -r near
2012-12-02 tile h12v04: 1 files warped
2012-12-03 tile h12v04: 1 files warped
```

It looks like I should find `testout/h12v04/h12v04_2012337_MCD_indices.tif` in my outdir?  I can't find it:

```
$ tree testout/
testout/
└── h12v04

1 directory, 0 files
```

What should I find in the outdir?

**Comment by bhbraswell** [comment]
I actually don't know what gips_tiles is supposed to do :-/

BTW it's generally OK to to paste printouts as far as I know.

**Comment by ags-tolson** [comment]
I've come to know that the symlinks in question have a funny unofficial syntax that is spoken by gdal, but for some reason they have the names of tif files:

```
h12v04_2012337_MCD_quality.tif -> HDF4_EOS:EOS_GRID:"/home/tolson/src/gips/data-root//modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.006.2016112013509.hdf":MOD_Grid_BRDF:Snow_BRDF_Albedo
h12v04_2012337_MOD_temp8tn.tif -> HDF4_EOS:EOS_GRID:"/home/tolson/src/gips/data-root//modis/tiles/h12v04/2012337/MOD11A2.A2012337.h12v04.005.2012346152330.hdf":MODIS_Grid_8Day_1km_LST:LST_Night_1km
h12v04_2012338_MCD_quality.tif -> HDF4_EOS:EOS_GRID:"/home/tolson/src/gips/data-root//modis/tiles/h12v04/2012338/MCD43A2.A2012338.h12v04.006.2016112020013.hdf":MOD_Grid_BRDF:Snow_BRDF_Albedo
```

**Comment by matthewhanson** [comment]
GDAL actually ignores the file extension when it tries to read a file, and instead tries to open it with whatever driver works.   The symlinks of course are broken for normal use, but if you try to read that output symlink with GIPPY, it points to a subdataset in the HDF file instead and opens it appropriately.

It's a bit of a hack, but allows GIPS to create virtual products: products that already exist in an HDF file without having to copy the data over to a new file.   The extension could just as easily be absent I suppose, although I think that might cause problem when GIPS is looking for files if the regex or pattern includes the tif extension.

**Comment by ags-tolson** [comment]
Wow, okay, that's bizarre, but I see how it'd be necessary or useful.  `gips_project` generates a real tif with real content, so I guess that half of this issue is closed.  Thanks so much for pointing me in the right direction.

**Comment by matthewhanson** [comment]
Yes, gips_project will read the HDF (via the links) and use gippy to warp and combine them into the project files.   I admit it's pretty hacky, but with a file-based inventory system there really wasn't a good alternative.   Moving to using a database for inventorying as you guys are doing will make this sort of thing unnecessary.

Glad I could help.

**Comment by demiurg** [comment]
I think as long as these files are supposed to be opened with gdal, gdal vsi or band notation in symlinks are a good way to simplify things in gips and delegate to gdal. Should even work on windows.

**Comment by ags-tolson** [comment]
Pretty sure there's no actual work here, just me not understanding the way gdal/GIS uses symlinks uniquely when I was new.
