### ISSUE TITLE
new inventory architecture sketch

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#56]
Before we can get started on creating the new inventory, we need a reasonable sketch of what it will do, how it will work, etc. 

Ian, Rob, Pavel and Justin have met about this, but need to formalize.  

Need to create a general design specification with rough LOE

Some thoughts on things that need to be considered:
* DB design -- addition of asset status
* Locking down the data archive/repo
* Necessary changes to existing gips tools to use new inventory
* Impacts on and requirements of yet-to-be-designed scheduler

**Comment by justinfisk** [comment]
In addition to asset 'status', DB also should record number of clients waiting on the same task for job scheduling priority.

**Comment by ags-tolson** [comment]
See also #16 for more discussion.

I ran a little search of the filesystem to try to get a rough handle on scale:

```bash
$ for x in {aod,cdl,daymet,landsat,merra,prism,sar,sarannual,weld}; do find $x > ~/inv/$x.find;  done
$ # modis info was gathered separately . . .
$ $ wc -l ~/inv/*
        1 /home/tolson/inv/aod.find
        1 /home/tolson/inv/cdl.find
  3251753 /home/tolson/inv/daymet.find
   228205 /home/tolson/inv/landsat.find
   105917 /home/tolson/inv/merra.find
  1418101 /home/tolson/inv/modis.find
    30843 /home/tolson/inv/prism.find
        1 /home/tolson/inv/sarannual.find
        1 /home/tolson/inv/sar.find
    25351 /home/tolson/inv/weld.find
  5060174 total
$ # ^^^ approx 5 million but includes directories, misc. junk files, and whatever else is in there
```

I believe tables with roughly several million rows are okay for postgres (we'll probably have several tables with foreign keys etc but even if row count explodes for one or more of them, I guess 50 to 100 million rows is about as bad as it gets).  Also I presume the ongoing intent is to store file metadata and paths in the new inventory, not file contents, so I assume `.hdf` and `.tif` file sizes aren't relevant.

I think there was talk of storing GIS data in gips' new inventory though, such as vectors, so that postgis is probalby required.

What other data (and metadata) will be stored?

**Comment by ags-tolson** [comment]
(@ircwaves you should probably know about this discussion; sorry if GH already notified you)

I've been thinking about our development plans.  Maybe we can separate the inventory from the async/scheduling/management pieces, and so design & implement the inventory component first, then pivot to the other stuff, using the completed inventory system as a foundation.

To prevent confusion, by 'inventory' I mean the DB, ORM, appropriate schema and an API, all for keeping comprehensive metadata for a GIPS data repo, such that GIPS itself doesn't have to do any filesystem scanning any more, and can instead make calls.  Here's a rough draft of a call:

```python
from gips import inventory # or something
sources = inventory.sources('modis', product='MOD', dates=(start, end), extents)
assert sources.paths == ('modis/some/crazy/path/XXX.YYY.ZZZ.WHATEVER.hdf', . . . )
```

**Comment by bhbraswell** [comment]
I think the inventory system should know about users and projects (or some label that can indicate projects). Is that the plan?

**Comment by demiurg** [comment]
what are users to gips?

**Comment by bhbraswell** [comment]
Anyone who uses GIPS?

**Comment by justinfisk** [comment]
it will need to allow multiple users/projects

**Comment by ags-tolson** [comment]
@bhbraswell late answer but yes, later on . . . mostly I was commenting on planning our attack rather than discussing features per se.

Speaking of which I started a document to record my understanding of the intended results of this development effort:  https://goo.gl/A4Poyg

I would really appreciate it if folks would have a look and leave comments; I'll update the doc accordingly, and then hopefully as we go we'll have a more and more comphrehensive written text describing our goals.

**Comment by demiurg** [comment]
ok, i understand now that unix users and all created gips project will be saved in this 'inventory'

**Comment by justinfisk** [comment]
I think the DB should also store what version of gips generated the product granule.

**Comment by ircwaves** [comment]
And that should be duplicated in the metadata of the geotiff as well, so that as the data proliferates, it is traceable.

**Comment by demiurg** [comment]
Here is what I think the order of work items for this is:

1. set up Django project settings file
2. add models to store files, users, project, commands
3. replace filesystem calls with database queries

preliminary models are:

Command: created(timestamp), command(text) 
File: filepath(text), product(text), sensor(text), created(timestamp), project(many-to-many Project)
Project: filepath(text), created(timestamp), modified(timestamp), owner(User)
User: username, first_name, last_name, email, password (Django User)

My rough estimate is about 40 hours to do the above. I purposefully made it not spatial and simple for the first version.

**Comment by ags-tolson** [comment]
:+1: to prototype plan.

If you want to write a demo of your prototype concurrently with your prototype, you could write prototype tests to test your prototype so you can test and demo while you prototype.

![](https://imgflip.com/s/meme/Yo-Dawg-Heard-You.jpg)

**Comment by demiurg** [comment]
@justinfisk, pushed some models, as promised. User handling (initialization) might needs to be added, but you can set any field you dont want to use to null=True to try stuff.

**Comment by ags-tolson** [comment]
@justinfisk forget if you knew this but the branch is:

https://github.com/Applied-GeoSolutions/gips/tree/56-inventory

**Comment by justinfisk** [comment]
I did know that, but I appreciate the clarity.

**Comment by demiurg** [comment]
Unless I get further instructions, this can be closed or reassigned

**Comment by ags-tolson** [comment]
For now I've been asked to take ownership of this; for the first shippable effort I'm confining myself to the following:

> Write the basic inventory using real DB and API for internal GIPS use.  Don’t implement any notion of users, monitoring, services, or any of that; just make GIPS work with SQL tables.  The primary deliverable will be improved performance of gips commands (especially inventory).
> * Implement database table designs, including tests for any complex ORM usage.
> * Write the API, including tests for it.
> * Write just enough automated tests to have confidence that GIPS code changes are safe.
> * Carefully replace existing file-scanning system with DB-querying system.
> * Just enough automation and dev tools for convenient development, deployment, and testing.

(The above is taken from https://goo.gl/A4Poyg)

**Comment by ags-tolson** [comment]
Fix for this issue is in this PR, whose title is a bit misleading:

https://github.com/Applied-GeoSolutions/gips/pull/87

**Comment by ircwaves** [comment]
Well done!

**Comment by ags-tolson** [comment]
Follow-on work for this issue:  #97 has a list of drivers that need code changes to be compatible with the database inventory.

**Comment by ags-tolson** [comment]
Post-merge system tests:  Ran the modis fetching system test successfully 4 of 5 times (see #111).   Rest of the system tests passed normally.  Note `--setup-repo` was only used for prism; otherwise I used source data I keep for the purpose.
