### ISSUE TITLE
landsatAsset chokes on hyphens in the asset's path

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#61]
Clipped from a pytest run:

```
filename = '/data-root/landsat/stage/LC80120302015352LGN00.tar.bz'

    def __init__(self, filename):
        .
        .
        .    
        if "-" in filename:
            VerboseOut('SR asset', 2)
            self.asset = 'SR'
            self.sensor = 'LC8SR'
>           self.version = int(fname[20:22])
E           ValueError: invalid literal for int() with base 10: '0.'
```

**Comment by bhbraswell** [comment]
Yuck. It’s trying to catch files that look like this:

LC81200612015149-SC20151121043437.tar.gz

These are Landsat 8 surface reflectance data (a separate data set from TOA radiance), and not available by fetch.

**Comment by ags-tolson** [comment]
Fix is in this commit in branch in `46-landsat`:

ad75d3f5cc81815ecb2b094d2376566a77044345
