### ISSUE TITLE
most MODIS data require http auth to fetch

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#63]
As of yesterday, MODIS fetching is broken for everything that comes from http://e4ftl01.cr.usgs.gov/.

Official notice:  https://lpdaac.usgs.gov/about/news_archive/important_changes_lp_daac_data_access

https://lpdaac.usgs.gov/faq-page <-- official explanation, which can't link internally so here's the important stuff:

> The Earthdata Login provides a single mechanism for user registration and profile management for all EOSDIS system components (DAACs, Tools, Services). Your Earthdata login also helps the EOSDIS program better understand the usage of EOSDIS services to improve user experience through customization of tools and improvement of services. EOSDIS data are openly available to all and free of charge except where governed by international agreements.
> 
> Once you have created an Earthdata login account, you will need to authorize the LP DAAC Data Pool application in order to download data from Data Pool, DAAC2Disk, Command line scripts, EarthExplorer, and GloVis.
> 
> To accomplish this, simply log in to your account from the Earthdata Login page, and click on “My Applications” in the title bar. You will be presented with a list of approved applications. At the bottom of the list click the “Approve More Applications” button. Type in “LP DAAC Data Pool” in the text box and hit enter. In the application search results click the check box next to “LP DAAC Data Pool” and then click the “Approve Selected Applications” button. The next page will allow you to select what information you send. Select the appropriate options and click “Authorize”.  You should be returned to the approved applications page with a green confirmation bar acknowledging your request.
> 

My favorite part of all this is that they tell you how to use unix commands to access auth-protected data by linking to a microsoft word document:

https://lpdaac.usgs.gov/sites/default/files/public/get_data/docs/Command%20Line%20Access%20Tips%20for%20Utilizing%20Earthdata%20Login.docx

**Comment by ags-tolson** [comment]
Branch (no commits atm):  https://github.com/Applied-GeoSolutions/gips/tree/63-modis-auth

**Comment by ags-tolson** [comment]
Things to do:
- [ ] Cover `modisAsset.fetch()` with unit/int tests
- [ ] Mull 'requests' lib auth support and see if it's worth switching: http://docs.python-requests.org/en/master/
- [ ] Shore up error handling & reporting in `modisAsset.fetch()` for graceful auth failures
- [ ] Work out password & possibly cookie storage (`.netrc`?)
- [ ] Operational question:  One Login for each gips installation, or is it per-user?  (Also may need to establish a gips MODIS user in Earthdata.)

**Comment by bhbraswell** [comment]
Consider merging #53 which updates MODIS to Collection 6 along with this fix.

**Comment by ags-tolson** [comment]
Okay; what I'll probably do is merge when it's complete then look at #53 after.

**Comment by ags-tolson** [comment]
Having problems downloading data right now.  #61778 is my ticket number with the earthdata people for sorting out the problems getting hdf files via wget and python libs (rob's tried requests, I tried urllib2, no programmatic access seems to work right now).  I clicked the support link on https://urs.earthdata.nasa.gov/

**Comment by bhbraswell** [comment]
Easier test case is an XML metadata file (what I'm trying to get for ASTER):
```
http://e4ftl01.cr.usgs.gov/ASTT/AST_L1T.003/2000.04.29/AST_L1T_00304292000010042_20150409113636_37952.hdf.xml
```

**Comment by ags-tolson** [comment]
No luck for that URL for me in wget; also tried curl for previous URLs and the one you just pasted, similar bad results.

**Comment by bhbraswell** [comment]
Yeah, but works using chrome and safari (with password). As you stated above.
If they are doing it intentionally it could have a pretty significant effect of our ability to do stuff.

**Comment by matthewhanson** [comment]
In Chrome Developer Tools, you can right click the request in the Network tab and get the curl requests that are being made.   Which look like this:



```
# initial request
curl 'http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/MCD43A4.A2000113.h35v09.005.2006278081111.hdf.xml' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/' -H 'Cookie: _ga=GA1.2.2108586845.1456602254' -H 'Connection: keep-alive' --compressed


# authorize
curl 'https://urs.earthdata.nasa.gov/oauth/authorize?app_type=401&client_id=ijpRZvb9qeKCK5ctsn75Tg&response_type=code&redirect_uri=http%3A%2F%2Fe4ftl01.cr.usgs.gov%2Foauth&state=aHR0cDovL2U0ZnRsMDEuY3IudXNncy5nb3YvTU9UQS9NQ0Q0M0E0LjAwNS8yMDAwLjA0LjIyL01DRDQzQTQuQTIwMDAxMTMuaDM1djA5LjAwNS4yMDA2Mjc4MDgxMTExLmhkZi54bWw' -H 'Authorization: Basic ZGV2c2VlZDp1ajY2amRvS3pnZkNVdw==' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent:M pozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/' -H 'Cookie: __utma=259910805.406250338.1457540566.1457540566.1457540567.2; __utmz=259910805.1457540567.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.3.1971228756.1456953803; _ceg.s=o8iloi; _ceg.u=o8iloi; _urs-gui_session=MkVOeEJwc1RmZWZCSGRTRnR2d3BEeDV4aGdMVHl5MURVYk1kQnNYVHhtKzRwb1JlQmFLQ2Ixc3lpSWhBV1pISnZuMlEyRjZGS0s1N282d1pwZ1NkQ3UzMUpQOGF1RnNtc3ZyMGk3MllCVit2d2lzTzdmcE9ldHFxUElFVit6QkdCR1E4UEhHMmR4cm4ydjZrbHBJaFk5NzZrWklyT1dKS2IrUE5RMG44eC9BaG1pL0ZldzUzWkkrZEllOHBIS2VkLS1yNUUyakJuM1NBazVWdnVzc0hCZkNBPT0%3D--54f586f41d5c86f464c29ee6c3cab18b7a2ffc99; _ga=GA1.2.1971228756.1456953803; _ga=GA1.4.1971228756.1456953803; _ceg.s=oas1w4; _ceg.u=oas1w4' -H 'Connection: keep-alive' --compressed


# oauth
curl 'http://e4ftl01.cr.usgs.gov/oauth?code=aca05194c23a5df8c46bd9493ec776260397619c1b7df7b10221bfeb5ae50ed7&state=aHR0cDovL2U0ZnRsMDEuY3IudXNncy5nb3YvTU9UQS9NQ0Q0M0E0LjAwNS8yMDAwLjA0LjIyL01DRDQzQTQuQTIwMDAxMTMuaDM1djA5LjAwNS4yMDA2Mjc4MDgxMTExLmhkZi54bWw' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/' -H 'Cookie: _ga=GA1.2.2108586845.1456602254' -H 'Connection: keep-alive' --compressed


# final request
curl 'http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/MCD43A4.A2000113.h35v09.005.2006278081111.hdf.xml' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://e4ftl01.cr.usgs.gov/MOTA/MCD43A4.005/2000.04.22/' -H 'Cookie: _ga=GA1.2.2108586845.1456602254' -H 'Connection: keep-alive' --compressed
```

However, these requests are the ones being made from the app, which is the MODIS site...user authentication occurs via Basic Auth, and the site responds with redirects that authorize the user, fetch a token, then use the token.     I don't think any of this should be necessary here, but clearly something is wrong, I've also been unable to get python requests or urllib auth working.    

With logging enabled on the requests module, you can see that from the initial request follows the redirects, but depending on what I try it either hangs or just returns an unauthorized error.

**Comment by ags-tolson** [comment]
Thanks @matthewhanson that's a good tip and more good data.

Meanwhile I got a response from support@earthdata.nasa.gov and sent a reply; nothing of consequence has been said yet though.

**Comment by matthewhanson** [comment]
@ags-tolson @ircwaves @bhbraswell 

We talked about this some more here.  So the auth protocol is really designed to authenticate through a browser by using a form.    That application is authorized through the central oauth server.  This is auth system twitter uses, as well as GitHub, for authorizing third party apps.   For programmatic access I think it would involve doing the initial authorization and then retrieving a non-expiring token.   Interested to hear what the earthdata folks say.   We've got a few people I can reach out to as well.

Fortunately, there is a work-around.   The anonymous FTP site is still active.   You'll need to reform the filename as the folder naming convention is different....although you could still use the name as formed from the MODIS html page scraping, the unknown portion of the filename (the processing date) is the same from both http and ftp.

ftp://ladsweb.nascom.nasa.gov/allData

With folders as collections, e.g., 5, 51, 6..

@bhbraswell do you know of any other differences between the ftp and http sites?   Is the latency the same?

I think the FTP is slower, but it's a stop-gap until the auth issue is worked out.

**Comment by bhbraswell** [comment]
Good catch on the ftp Matt, I had no idea. Slower, yes for some reason it seems so. Contents and latency appear to be OK for MODIS, e.g. the last MODIS MCD43 collection 6 is only a week and a half old.

However the bad news, for me, is that the ASTER data are not there. I think it will be worth the effort, for me, Al Franken, to continue to try to access the data pool. According to @ags-tolson, based on his exchange with them, there doesn't seem to be a policy against programmatic access, so that's the good news.

**Comment by bhbraswell** [comment]
So this seems to work for me: 
```
wget -L --user USER --password PASSWORD --load-cookies ~/.cookies --save-cookies ~/.cookies http://e4ftl01.cr.usgs.gov/ASTT/AST_L1T.003/2002.05.11/AST_L1T_00305112002003107_20150426033306_21980.hdf.xml
```
But so did this:
```
wget -L --user USER --password PASSWORD http://e4ftl01.cr.usgs.gov/ASTT/AST_L1T.003/2002.05.11/AST_L1T_00305112002003107_20150426033306_21980.hdf.xml
```
So that's confusing. It seems like the "L" (follow redirects) is the important thing, not necessarily the cookies, but why?

In any case python requests with allow_redirects=True didn't magically solve the problem.

**Comment by ircwaves** [comment]
Just like the real life, the 'Al Franken' just confuses things.  (I'll go back to tillage ReportLand)

**Comment by bhbraswell** [comment]
```
import commands
import tempfile

def get(url, auth):
    outfile = tempfile.NamedTemporaryFile(delete=True)
    format = {'user': auth[0], 'password': auth[1], 'url': url, 'outfile': outfile.name}
    command = "wget -L --user {user} --password {password} {url} -O {outfile}".format(**format)
    status, output = commands.getstatusoutput(command)
    content = outfile.read()
    return content
```

**Comment by ircwaves** [comment]
I don't see this posted here, but this is a good overview of how the EarthData Oauth2/SSO protocol should go, theoretically: [SSO Client Implementation](https://urs.earthdata.nasa.gov/sso_client_impl)

**Comment by ags-tolson** [comment]
I got another reply from the support people with a possible remedy; will try it tomorrow:

> We found scope error in our logs. The user has authorized the application, but I'm guessing only with limited fields (what we know as the 'scope'). 
> So for example, the user may have authorized the LPDAAC Data Pool access to their user ID and email address, but not the other fields. 
> Meanwhile, the LPDAAC data pool is requesting the entire user profile, and it is being denied, resulting in a 403. Try doing the following:
> 1) In the URS GUI, go to the 'My Applications' page, and revoke the authorization by clicking on the 'X' for the LP DAAC Data Pool application. 
> 2) Click on the 'Approve More Applications' button, and search for 'LP DAAC DATA POOL'
> 3) Check the box for the LP DAAC Data Pool application, and then click on the 'Approve Selected Applications'
> 4) Leave the Country, User Type, Affiliation, and Study Area checkboxes ticked. You may uncheck the notification checkbox. Then click 'Authorize'.
> Hope this helps. Let me know how it goes. 
>

**Comment by bhbraswell** [comment]
There doesn't appear to be an LP DAAC DATA POOL application. I'll try checking everything with an LP DAAC in it.

**Comment by bhbraswell** [comment]
Now I can't get anything, not even through the browser:

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at root@e4ftl01.cr.usgs.gov to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
>

**Comment by ircwaves** [comment]
I know it doesn't apply, but I can't fight it: "Is it Wednesday?"

Back on topic: [python-oauth2](https://github.com/joestump/python-oauth2) library might be worth a shot.  What do you guys think?  I fully admit that I haven't dug into any of this, but if earthdata has gone Oauth2, maybe this would be a good (100% test coverage) library to use?

**Comment by ircwaves** [comment]
Not that using `python-oauth2` would help in the event of ISEs.

**Comment by ags-tolson** [comment]
Okay, I think their process works and I think they're right about the cause:  I think I remember unchecking some of the boxes they say must not be touched when adding the Data Pool to my account's list of approved applications.

**Comment by matthewhanson** [comment]
I've tried both python-oauth2 and python_oauth2, (yes they are two different libraries), but they did not work.

So here the 'app' is the MODIS download website.   Another approach would be to create this app as a separate app entirely, it would get it's on access token and would need to be authorized on the URS website.    In this case that's when you would use python-oauth2.    Hopefully this isn't necessary and @ags-tolson latest info will work.   If it does all that should be necessary is basic auth to the website, and it takes care of the ugly behind the scenes oauth2 stuff.

**Comment by bhbraswell** [comment]
My ASTER script just started working again. I guess it's safe to assume that the NASA people are making frequent changes to the system.

**Comment by ags-tolson** [comment]
Looks like requests can do the job:

```python
import os, requests

fname = 'requests-MYD11A1.A2012336.h12v04.005.2012341040543.hdf'
url  = 'http://e4ftl01.cr.usgs.gov/MOLA/MYD11A1.005/2012.12.01/MYD11A1.A2012336.h12v04.005.2012341040543.hdf'
kw = {'timeout': 10, 'auth': ('ags.tolson', os.environ['PASSWORD'])}

resp = requests.get(url, **kw)

with open(fname, 'wb') as fd:
    for chunk in resp.iter_content():
        fd.write(chunk)
```

```
(.venv) laptop2:~/src/gips$ ls -lh requests-MYD11A1.A2012336.h12v04.005.2012341040543.hdf 
-rw-r--r-- 1 tolson staff 1.3M Jul 28 13:23 requests-MYD11A1.A2012336.h12v04.005.2012341040543.hdf
```

**Comment by matthewhanson** [comment]
Great to hear.  Looks like they've fixed something on there end since that's the same code I had originally tried.   Thanks!

**Comment by ags-tolson** [comment]
Inventory tests are passing in `dev`:

```
py.test --clear-repo --src-altering -k 'inv_fetch' -s -vv --ll debug
```
