### ISSUE TITLE
`gips_process modis` breaks for too many products

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#70]
On `gips_process` runs with no product specified and the date 2012-12-02, ndvi8 causes an error.  Other products also result in an error later on in the run if additional days are specified (eg `-d 2012-12-02,2012-12-03`).  Deactivating ndvi8 seems to fix the other products.  The errors don't occur on a second run right after the first, nor if the 2012-12-03 is specified by itself.  Repeat the problem with:

`gips_process modis -s NHseacoast.shp -d 2012-12-02,2012-12-02 -v 4`

The error seems to be bubbling up from gdal, from this line near as I can tell:

https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdaldataset.cpp#L2846

The error itself (similar ones are produced for cloud on the next day's run) seems to be misreported as I could find no discernible difference in the file in question between runs that fail and those that succeed:

```
runtime error
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/inventory.py", line 285, in process
    self.data[date].process(*args, **kwargs)
  File "/home/tolson/src/gips/gips/tiles.py", line 76, in process
    [t.process(*args, products=self.products.products, **kwargs) for t in self.tiles.values()]
  File "/home/tolson/src/gips/gips/data/modis/modis.py", line 956, in process
    refl = gippy.GeoImage(allsds)
  File "/home/tolson/src/gips/.venv/local/lib/python2.7/site-packages/gippy/gippy.py", line 4741, in __init__
    this = _gippy.new_GeoImage(*args)
RuntimeError: 4: `HDF4_EOS:EOS_GRID:"/home/tolson/src/gips/data-root//modis/tiles/h12v04/2012337/MOD09Q1.A2012337.h12v04.005.2012346141041.hdf":MOD_Grid_250m_Surface_Reflectance:sur_refl_b02' does not exist in the file system,
and is not recognised as a supported dataset name.
```

It may be relevant that the loop just increased in iterations due to modis 6 changes, in particular more products are made for 2012-337 due to MCD43 assets being available for that day that didn't used to be.

**Comment by ircwaves** [comment]
appears fixed by 903235c

**Comment by ircwaves** [comment]
I may have closed too soon, looks like ndvi8 is just deactivated, squelching the issue (903235c).  I will see if the issue persists when I address #31

**Comment by bhbraswell** [comment]
See branch ndvi8

**Comment by bhbraswell** [comment]
Looking at the original issue. Actually seems like we might have had a bad index file clogging things up.

**Comment by bhbraswell** [comment]
@ags-tolson just FYI I believe that @ircwaves  and I changed this directly on main. If it passes your tests then we can close the issue.

**Comment by ags-tolson** [comment]
The test `t_process` emits a false positive in `dev` right now, meaning it passes when it should fail.  It should fail because a new product file should be present that the test doesn't expect, named something like `h12v04_2012337_MOD_ndvi8.tif`.  The command line I used to find this out was:

`time py.test --ll debug -s -x -vv --sys -k'modis and process'`

What you want to do next is go through the commit that turned off ndvi8 and revert any changes you think would correct the problem.  Also further tests may need rework to add ndvi8 back in, such as `t_project` for instance.  Likewise don't forget to revert stale comments.  Here's the commit:  903235c

For now I'm going to continue to prioritize the data handler, so this issue needs to be reassigned so someone who will do the work.

**Comment by bhbraswell** [comment]
I'm going to need to talk about this with one of you before I can do anything.

**Comment by bhbraswell** [comment]
Reassigning to @ircwaves pending discussion. Where I'll leave it is that I believe the code I pushed, only removing comment lines, "works for me" (WFM). On my GIPS installation, it retrieves the data and they are what I expect.

**Comment by bhbraswell** [comment]
Wrong, it doesn't work in our test mode (no "-p"). 

It fails on the line 

```
refl = gippy.GeoImage(allsds)
```

where ```allsds``` is a list of HDF file contents:

```
In [11]: allsds
Out[11]: 
['HDF4_EOS:EOS_GRID:"/data/gips/modis/tiles/h12v04/2005001/MOD09Q1.A2005001.h12v04.006.2015099030619.hdf":MOD_Grid_250m_Surface_Reflectance:sur_refl_b01',
 'HDF4_EOS:EOS_GRID:"/data/gips/modis/tiles/h12v04/2005001/MOD09Q1.A2005001.h12v04.006.2015099030619.hdf":MOD_Grid_250m_Surface_Reflectance:sur_refl_b02',
 'HDF4_EOS:EOS_GRID:"/data/gips/modis/tiles/h12v04/2005001/MOD09Q1.A2005001.h12v04.006.2015099030619.hdf":MOD_Grid_250m_Surface_Reflectance:sur_refl_state_250m',
 'HDF4_EOS:EOS_GRID:"/data/gips/modis/tiles/h12v04/2005001/MOD09Q1.A2005001.h12v04.006.2015099030619.hdf":MOD_Grid_250m_Surface_Reflectance:sur_refl_qc_250m']

In [12]: refl = gippy.GeoImage(allsds)

```
Oh look! It works in a separate python interpreter window, but not in the driver issuing the exact same statement!

**Comment by bhbraswell** [comment]
Solution: comment it back out again. Per conversation with Nate T. I don't believe we need the product right now. However, this represents a general GIPS failure since he decided to go get the data himself and do his thing manually.

**Comment by bhbraswell** [comment]
So, that was incorrect. The ndvi8 product is indeed needed for general use as soon as possible.

I believe it's possible to have the product available only as a "-p" option and not looped over. That would be acceptable.

BTW the issue as noted above does not appear to be specifically a gippy problem, as gdal.Open() also does not return anything at the same point in the code.

**Comment by ags-tolson** [comment]
update:  It looks a lot like some underlying problem in gippy or GDAL is causing the crash, and it seems to happen when too much processing happens in the wrong order.  When the crash happens, seemingly a product in the rear part of the list is what breaks, not ndvi8, which just so happened to be at the back.

@ircwaves is working on fixing the underlying problem by altering gippy.  I have a workaround stashed to raise an error just before the product count climbs too high; the error message explains the problem and suggests -p.

**Comment by ircwaves** [comment]
So, notes from my investigation:

0. gdal1.x seems to have a limit of 32 opened subdatasets (this may be a peculiar to the HDF4 driver)
1. This is fixed in gdal2
2. The fix until we move to gdal2 is to ensure that all GeoImage and GeoRaster objects are `None`ed or `del`ed after each loop iteration.

@ags-tolson will you please go through the modis driver and make sure all gippy objects are None'ed when they're done being used?

**Comment by bhbraswell** [comment]
Thanks -- 2. is the immediate need then.

**Comment by ags-tolson** [comment]
@ircwaves okay I'll update this comment with anything I find

**Comment by ircwaves** [comment]
Cool...and I forgot to mention that I have a script which demonstrates the issue, and I would be happy to demo it for you outside of gips.

**Comment by ags-tolson** [comment]
https://github.com/Applied-GeoSolutions/gips/pull/184 <-- fix

**Comment by ags-tolson** [comment]
#185 merged back in early Jan, closing.

**Comment by ircwaves** [comment]
And for one more step, I'll close the issue.

**Comment by ags-tolson** [comment]
ugh sorry, thanks
