### ISSUE TITLE
base classes

### ISSUE THREAD

**Issue by demiurg** [Applied-GeoSolutions/gips#72]
I am adding an abstract class for now, for inventory. I'm not sure if it's actually a good idea, or whether anyone should really be able to extend inventory. 

Drivers might also have a base class. Right now there is just a class that does implement a bunch of stuff. Is there some functionality that we want every driver to implement? I think so.

**Comment by ircwaves** [comment]
As indicated by the CDL driver+, there are some drivers that essentially only need to specify where the data is and how it is organized.  The comments in the base driver classes++ indicate which methods are likely to be need overriding for some data drivers.

    + https://github.com/Applied-GeoSolutions/gips/blob/dev/gips/data/cdl/cdl.py
    ++ https://github.com/Applied-GeoSolutions/gips/blob/dev/gips/data/core.py
