### ISSUE TITLE
improve asset revision management

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#74]
Collections represent large scale announced revisions of data (ie Modis collection 6).  However sometimes an asset is updated within a collection, such as a regenerated file to remove errors.  Artificial example:
- old version:  `MYD11A1.A2012338.h12v04.005.2012341075802.hdf﻿⁠`
- new version:  `MYD11A1.A2012338.h12v04.005.2015123456789.hdf﻿⁠`

Currently GIPS doesn't handle these revisions well, necessarily.  If multiple versions of a file get into the archive/repo, then only the newest will be used when building an inventory at startup time.  Also to delete an old version on acquisition of a new one, `--update --fetch` must be specified, however there's no clear UX for letting the user know that an updated file is available or has been acquired; they have to guess.

Add a mechanism to the inventory subsystem to let it optionally throw out old revisions, and to notify users when new ones become available.  It should also avoid preventing drivers from implementing multiple revisions if they wish (such as table constraints on the uniqueness of a revision timestamp).

_Edit:  Incorporate @ircwaves' correction of current behavior._

**Comment by ircwaves** [comment]
One point, the base `gips.data.core.Asset.archive` method's current behavior is to remove an old version before adding the new version ([code here](https://github.com/Applied-GeoSolutions/gips/blob/dev/gips/data/core.py#L431))*.  Perhaps the trick is to somehow have the 



* as a bonus, there are multiple less-than-awesome exception/assertion statements in the vicinity

**Comment by ircwaves** [comment]
Note that some improvements have happened in this area (#410) , which includes specifically addressing the modis versioning issue:
https://github.com/Applied-GeoSolutions/gips/blob/22c9bfb64720113d311444cfac2d4a33630664a6/gips/data/modis/modis.py#L179-L180

The one point that remains to be addressed here is to handle versions better when fetching, specifically fetch should handle examining versioning BEFORE downloading, which is currently handled in the opposite order.  For clarity, @ags-tolson , would you consider most of this issue addressed?  And perhaps we can close and move the fetch-related but to its own issue?

**Comment by ags-tolson** [comment]
I think handling updates in the query step is a great idea; that seems like a separate issue to me too.  I checked on the UX issue I put into the issue description, and it looks like `_archivefile` tells the tale with verbose-outs, so I guess we're good to close this issue.
