### ISSUE TITLE
degenerate asset file names break modisAsset.__init__

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#79]
Randomly in the central repo I found files that looked like:

`modis/tiles/h12v09/2006012/MOD11A1.A2006012.h12v09.005.hdf`

But they're supposed to look like:

`modis/tiles/h12v09/2006008/MYD11A1.A2006008.h12v09.005.2008096033608.hdf`

Although they weren't supposed to be there, they still broke the constructor due to an off-by-one error while parsing filenames into metadata.

Remove the degenerates (saving them to a junk dir for while just in case), while improving the shell glob that produces the filename so it protects the parsing step.

**Comment by ircwaves** [comment]
bueno.  note that 0.9.0 is the pre-push version of gips that I still need to tie off.

**Comment by ags-tolson** [comment]
K imma do code bit first then ops bit second for to make glorious benefit software release

![](https://66.media.tumblr.com/avatar_cfc25e75654c_128.png)

**Comment by ags-tolson** [comment]
degenerate files removed via `find -not -name 'M??????.A???????.h??v??.???.?????????????.hdf' -name '*hdf' | tee miscreants` followed by `xargs rm <miscreants`

**Comment by ircwaves** [comment]
bueno.
