### ISSUE TITLE
Asset.updated() crashes every time

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#85]
Looks like a capitalization problem.  I think it should be `raise NotImplementedError('...')` though since apparently the subclasses have to do it.

https://github.com/Applied-GeoSolutions/gips/blob/3ac0bd80ef7360a10ccbbf542b07bc9590604b31/gips/data/core.py#L219

**Comment by ircwaves** [comment]
T'is a capitalization problem.  Returning `False` makes it such that subclasses don't _have_ to do it, and everything will work.

**Comment by ircwaves** [comment]
Which `Asset` subclass did you discover this with?

**Comment by ags-tolson** [comment]
I found it by reading through `Asset` for #56.  Since the subclasses don't all define this method, fallback to the superclass method is pretty likely:

```
$ grep updated data/*/*.py
data/landsat/landsat.py:    def updated(self, newasset):
data/modis/modis.py:    def updated(self, newasset):
data/prism/prism.py:    def updated(self, newasset):
```

**Comment by ircwaves** [comment]
So, the reason it doesn't happen, is because those are the only three that have the possibliity of versioning at the moment.  And, if `--update` isn't passed along with `--fetch`, then `Asset.updated` is never called.

Good catch...as it never being hit would have made for extra confusion when it finally was hit.

**Comment by ags-tolson** [comment]
Thanks!  I want to lobby for `NotImplementedError` just a little bit more though:  If the user passes in `--update`, they have an expectation that an update will happen.  Silently ignoring that expectation via `return False` may not be as useful to the user as printing a polite error message and stopping, eg `--update not supported for merra.`  We could also print it as a warning and continue execution.

**Comment by demiurg** [comment]
Returning false is not a substitute for not implementing a method. Unless false is a valid default value that makes sense for that particular subclass.

**Comment by ircwaves** [comment]
Printing a warning and returning `False` "works" in the sense that if you don't implement asset versioning in your driver, then the `--update` switch won't work.

Raising `NotImplemented` could be made to work  better, with modification of the `archive` method to expect that possibility from `updated`.

Unless this is preventing the inventory, I will assign this bug to whomever is tasked with revamping exception handling throughout gips.  And via your lobbying efforts, the path forward should be `NotImplemented` raised and handled in `archive` is who it should be fixed.

You have both provided good insights that are very helpful.

**Comment by ags-tolson** [comment]
No, not impacting up the inventory work for #56.

Happy to help!  :+1:
