### ISSUE TITLE
pytest gets confused about escape sequences in strings in assertion diffs

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#91]
When you run a system test that has an assertion that compares strings containing escape sequences (ie terminal colors and bold etc), the diff can be erroneous by showing that a (nonexistent) difference exists at the escape sequences.  This is even more confusing when `-vv` hasn't been chosen at the command line, which means the _real_ difference isn't even shown.  The _assertion_ is always performed correctly, though, it's the _diff_ that's wrong:  It always shows extra diffs that are incorrect.

```
setup_landsat_data = None, repo_env = <gips.test.sys.util.GipsTestFileEnv object at 0x7fd7d7cee910>
expected = <gips.test.sys.util.GipsProcResult object at 0x7fd7d7cee950>

    def t_inventory(setup_landsat_data, repo_env, expected):
        """Test `gips_inventory` to confirm it notices the emplaced data file."""
        actual = repo_env.run('gips_inventory', *STD_ARGS)
>       assert expected == actual
E       assert GipsProcResult == GipsProcResult:
E         exit_status:  0 == 0
E         stdout:
E           - \x1b[1mGIPS Data Inventory (v0.8.2)\x1b[0m
E           ? ^^^^                               ^^^^
E           + GIPS Data Inventory (v0.8.2)
E           ? ^                               ^
E             Retrieving inventory for site NHseacoast-0
E             fname
E             LC80120302015352LGN00.tar.gz
E         Detailed information truncated (55 more lines), use "-vv" to show
```

**Comment by ircwaves** [comment]
I think this is addressed.  If we want to make this a feature request for removing colorification, we can, but the current system tests seem to handle this well with the addition of the `--expectation-format` switch to `conftest.py`.
