### ISSUE TITLE
modis system tests fail because *.hdf.index files depend on specific paths

### ISSUE THREAD

**Issue by justinfisk** [Applied-GeoSolutions/gips#92]
The modis system test t_inventory fails because the following files do not match the expected:

```
E           Differing items:
E           {'modis/tiles/h12v04/2012338/MCD43A4.A2012338.h12v04.006.2016112020013.hdf.index': 1671208837} != {'modis/tiles/h12v04/2012338/MCD43A4.A2012338.h12v04.006.2016112020013.hdf.index': 1011478975}
E           {'modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.006.2016112013509.hdf.index': 335987188} != {'modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.006.2016112013509.hdf.index': -635864639}
E           {'modis/tiles/h12v04/2012338/MYD11A1.A2012338.h12v04.005.2012341075802.hdf.index': -642783734} != {'modis/tiles/h12v04/2012338/MYD11A1.A2012338.h12v04.005.2012341075802.hdf.index': -29176720}
E           {'modis/tiles/h12v04/2012338/MOD10A1.A2012338.h12v04.005.2012341091201.hdf.index': 1725484908} != {'modis/tiles/h12v04/2012338/MOD10A1.A2012338.h12v04.005.2012341091201.hdf.index': 1849243119}
E           {'modis/tiles/h12v04/2012337/MCD43A4.A2012337.h12v04.006.2016112013509.hdf.index': -1583910758} != {'modis/tiles/h12v04/2012337/MCD43A4.A2012337.h12v04.006.2016112013509.hdf.index': 894841074}
E           {'modis/tiles/h12v04/2012338/MCD43A2.A2012338.h12v04.006.2016112020013.hdf.index': 1475653384} != {'modis/tiles/h12v04/2012338/MCD43A2.A2012338.h12v04.006.2016112020013.hdf.index': 513571033}
E           {'modis/tiles/h12v04/2012338/MOD11A1.A2012338.h12v04.005.2012341041222.hdf.index': 838676814} != {'modis/tiles/h12v04/2012338/MOD11A1.A2012338.h12v04.005.2012341041222.hdf.index': -256304483}
E           {'modis/tiles/h12v04/2012338/MYD10A1.A2012338.h12v04.005.2012340142152.hdf.index': -130649785} != {'modis/tiles/h12v04/2012338/MYD10A1.A2012338.h12v04.005.2012340142152.hdf.index': -1984921615}
```

Those index files contain information like this:

```
HDF4_EOS:EOS_GRID:"/data2/modis/tiles/h12v04/2012238/MOD10A1.A2012238.h12v04.005.2012241024733.hdf":MOD_Grid_Snow_500m:Snow_Cover_Daily_Tile
HDF4_EOS:EOS_GRID:"/data2/modis/tiles/h12v04/2012238/MOD10A1.A2012238.h12v04.005.2012241024733.hdf":MOD_Grid_Snow_500m:Snow_Spatial_QA
HDF4_EOS:EOS_GRID:"/data2/modis/tiles/h12v04/2012238/MOD10A1.A2012238.h12v04.005.2012241024733.hdf":MOD_Grid_Snow_500m:Snow_Albedo_Daily_Tile
HDF4_EOS:EOS_GRID:"/data2/modis/tiles/h12v04/2012238/MOD10A1.A2012238.h12v04.005.2012241024733.hdf":MOD_Grid_Snow_500m:Fractional_Snow_Cover
```

The path used to generate the 'expected' values is unlikely to match the configuration used to run the tests by other users. 

These files should either be excluded or (better) a smarter test should be written. 

For now, I have marked the test as expected to fail in a soon-to-be pushed branch.

**Comment by teks** [comment]
More info:  The checksums were generated originally on my machine, where the contents of the index files reflected my settings for REPOS in `gips/settings.py`, in other words `/home/tolson/...`.  Naturally the checksums are different on other people's machines, leading to test failures.  I think `GipsProcResult` can be extended to ignore specific files' checksums or else ignore the files completely.  That would be handy as this problem has come up before (e.g. landsat inventory fetch test).

**Comment by ags-tolson** [comment]
More info: The checksums were generated originally on my machine, where the contents of the index files reflected my settings for REPOS in gips/settings.py, in other words /home/tolson/.... Naturally the checksums are different on other people's machines, leading to test failures. I think GipsProcResult can be extended to ignore specific files' checksums or else ignore the files completely. That would be handy as this problem has come up before (e.g. landsat inventory fetch test).

**Comment by ags-tolson** [comment]
Partial fix for this in the branch `56-assets-and-products`

**Comment by ags-tolson** [comment]
additional fix ended up in `56-assets-and-products`; may end up being a full fix

**Comment by ircwaves** [comment]
Given that `ignored` key in the test results covers this sufficently, let's call it fixed.
