### ISSUE TITLE
cover all drivers with system tests

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#98]
Right now the system tests aren't complete:
- modis and landsat are "adequately" covered for now
- prism and merra have minimal coverage
- Other drivers have no coverage at all

Having good test coverage is important because each driver is permitted to do whatever it wants in its various subclasses in `gips/data/$DRIVER/$DRIVER.py`

**Comment by ircwaves** [comment]
Small progress update:
```
icooke@north:~/src/gips$ ls  gips/test/sys/ | grep '^t_.*.py$'
t_landsat.py
t_merra.py
t_modis.py
t_prism.py
t_repo_src_alteration.py
t_script_invocation.py
t_sentinel2.py
```
MERRA and PRISM tests are now adequate, and there is an AOD test in pipeline.

**Comment by ircwaves** [comment]
Looks like only `weld` and `sarannual` are testless:
```
icooke@north:~/src/gips$ for D in $(ls gips/data) ; do echo "====== $D ======" ; tree -P 't_*.py' gips/test/ | grep $D ; done
====== aod ======
│   ├── t_aod.py
====== cdl ======
    ├── t_cdl.py
====== chirps ======
│   ├── t_chirps.py
    ├── t_chirps.py
====== core.py ======
│   ├── t_core.py
    ├── t_core.py
====== daymet ======
    ├── t_daymet.py
====== __init__.py ======
====== landsat ======
│   ├── t_landsat.py
    ├── t_landsat.py
====== merra ======
│   ├── t_merra.py
====== modis ======
│   ├── t_modis.py
    ├── t_modis_asset.py
    ├── t_modis_fetch.py
====== prism ======
│   ├── t_prism.py
====== sar ======
│   ├── t_sar.py
    ├── t_sar.py
====== sarannual ======
====== sentinel2 ======
│   ├── t_sentinel2_fetch.py
│   └── t_sentinel2.py
    ├── t_sentinel2.py
====== weld ======
```
And as neither of those will get system tests until the testing framework is update, let's say huzzah and call this good for this milestone.

**Comment by bhbraswell** [comment]
Based on what people are using for current projects I think this is ok for the near future.

**Comment by ircwaves** [comment]
Right.  We keep increasing coverage.  It's good.
