### ISSUE TITLE
gips_inventory merra --fetch breaks

### ISSUE THREAD

**Issue by ags-tolson** [Applied-GeoSolutions/gips#99]
In `gips/test/merra.sh` there's this line a lot like this one, which I'm attempting to use as the basis for system tests for merra, which are needed for #56, since merra probably doesn't work properly with the database system right now:

`gips_inventory merra -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-02 -v 4 --fetch`

But none of the fetches work and generate tracebacks, see:

https://gist.github.com/ags-tolson/0127e58c1bb5e355c6ccc6d97c318933

Mainly:

```
Retrieving inventory for site NHseacoast-0
Retrieving data for bounds (-180.0, -90.0) - (180.0, 90.0)
Traceback (most recent call last):
  File "/home/tolson/src/gips/gips/data/core.py", line 807, in fetch
    cls.Asset.fetch(a, t, d)
  File "/home/tolson/src/gips/gips/data/merra/merra.py", line 300, in fetch
    data = dataset[asset][:, iy0:iy1, ix0:ix1].astype('float32')
  File "/home/tolson/src/gips/.venv/local/lib/python2.7/site-packages/pydap/model.py", line 192, in __getitem__
    return self.data[index]
  File "/home/tolson/src/gips/.venv/local/lib/python2.7/site-packages/pydap/proxy.py", line 116, in __getitem__
    dds, xdrdata = data.split('\nData:\n', 1)
ValueError: need more than 1 value to unpack
```

**Comment by ircwaves** [comment]
@justinfisk and @bhbraswell -- it looks like @ags-tolson does have your merra commits in his branch, did you end up testing out the merra fetch when you each updated the URLs for the atmospheric profile?

**Comment by ags-tolson** [comment]
If it's relevant, I checked and got the same results in dev (46b4632).

**Comment by ircwaves** [comment]
Yeah, good check.  I'm guessing that maybe `MERRA` also changed their data access, but wanted to see if justin or rob could confirm that it worked after the switch to MERRA2...which I assume it must have.

**Comment by bhbraswell** [comment]
It did work for me after the switch to merra2, at least for products tmin, tmax, srad, rhum, wind, and patm.

**Comment by ags-tolson** [comment]
@bhbraswell can you paste in your command line?

**Comment by bhbraswell** [comment]
No, since I unfortunately don't think I saved the command line in a script.

This is what I did but I don't think that is going to help you if it isn't working. 

```
gips_project merra -p tmin -s /net/nile/projects/IDS/amazon_boundary/amazon_cerrado.shp --res 0.5 0.5 -d 2010-001,2011-001 [or whatever] --outdir [whatever] --notld --tree -v4
```

**Comment by ags-tolson** [comment]
No worries, every little bit helps; thanks!

**Comment by bhbraswell** [comment]
As you can see, the problem line in the driver is

```
  File "/home/tolson/src/gips/gips/data/merra/merra.py", line 300, in fetch
    data = dataset[asset][:, iy0:iy1, ix0:ix1].astype('float32')
```

The error is actually happening in the pydap library. So, either the online resource doesn't exist (which is easy to check by going to the URL), or there is something about it that is not allowing the array slice to happen, e.g. they have changed the format of the data or how OpenDap is working for some reason. I think it's more likely that the resource isn't there. Let me know if you want me to look into it.

**Comment by bhbraswell** [comment]
Sorry - this is redundant with #118, in which we actually know the problem and are trying to fix it.
